<script type="text/javascript" src="/js/incomes/data.js?v=13"></script>
<style type="text/css">
    div.moxie_expenses_form_left table {
        width: 100%;
    }
    div.moxie_expenses_form_right table {
        width: 100%;
    }
</style>
<div id="form">
	<div class="moxie_expenses_form_div moxie_expenses_form_left">
		<?php
		echo $this->form;
		?>
	</div>
	<div id="search_box" class="moxie_expenses_form_div moxie_expenses_form_right">
		<?php
		echo $this->partial('common/filter.phtml', array('search_form' => $this->search_form));
		?>
	</div>
</div>