<script type="text/javascript">
	var message = "<?php echo "Guardado correctamente"; ?>";
function getSum() {
	var sum = 0;
	$('[id^=amount]').each(function() {
		sum += parseFloat(this.value);
	});
	sum = Math.round(sum * 100) / 100;
	document.getElementById('sum').innerHTML = '<b>' + sum + ' &euro;</b>';
}
$(document).ready(function() {
<?php
$s_url = Zend_Registry::get('config')->moxie->settings->url;
foreach ($this->categories as $key => $value) {
	$id = (isset($value['id3'])) ? $value['id3'] : $value['id2'];
	echo '
	$("#amount'.$id.'").change(function(){
		category = $("#category'.$id.'").val();
		amount = $("#amount'.$id.'").val();
		$("#amount'.$id.'").load("'.$s_url.'/budgets/add/category/"+category+"/amount/"+amount);
	})
	.ajaxStart(function() {
		$("#spinner").show();
	})
	.ajaxStop(function() {
		$("#spinner").hide();
	});
	';
}
?>
});

function snapshot() {
	$.ajax({url: '/budgets/snapshot',
		type: 'GET',
		data: '',
		success: function(data) {
			// show OK message
			$('#message').html(message);
		}}
	);
}
</script>

<h2 id="budget_title">
	<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
		<i class="material-icons" style="background-color: ##0b77b7">+</i>
	</button>
	<?php global $st_lang; echo $st_lang['budget']." ".$st_lang['press_here_display']; ?>
</h2>
<div id="budget_table" style="display: none;"categ>
	<table>
		<td>
<table width=100% style="max-width: 500px">

<?php
$f_initialBudget = 0;
foreach ($this->categories as $key => $value) {
	$id = (isset($value['id3'])) ? $value['id3'] : $value['id2'];
	echo '
	<tr>
	<td>'.$value['name1'].' '.$value['name2'].' '.$value['name3'].'</td>
	<td align="right">
	<input type="hidden" name="category'.$id.'" id="category'.$id.'" value="'.$id.'">
	<input type="text" id="amount'.$id.'" name="amount'.$id.'" onChange="getSum()" value="'.$value['budget'].'" style="text-align: right;">
	</td>
	<td width=15></td>
	</tr>
	';
	$f_initialBudget += $value['budget'];
}
?>
<tr>
<td></td><td align="right"><span id="sum"><b><?= $f_initialBudget?> &euro;</b></span></td>
<td><span id="spinner" style="display:none"><img src="/img/spinner.gif"></span></td>
</tr>
<tr>
<td colspan="2"><input type="button" value="Snapshot" onclick="snapshot();"></form></td>
</tr>
</table>
		</td>
		<td>
			<div>Presupuestos</div>
			<?php
			foreach ($this->st_budgetsList as $key => $value) {
				echo '
				<div>'.$value['date_created'].'</div>
				';
			}
			?>
		</td>
	</table>
</div>
<br><br>