<div id="categories_table" class="form-group accordion-body <?php if ($this->categories_collapse) { echo "collapse"; } ?>">
<?php
global $st_lang;
echo $this->categories_form;
?>
<ul width=100% id="categories_list" class="categories_list ">
<?php
foreach ($this->categories_list as $key => $value) {
	if (!empty($value['parent1'])) {
		$first_name = (!empty($value['name1'])) ? $value['name1']." --- " : "";
		echo '<li><input type="hidden" name="'.$value['id1'].'"/><a href="/categories/edit/id/'.$value['id1'].'"><img src="/img/edit.png"></a>';
		echo '<span class="categories_list">'.$first_name.$value['name2']."</span><span>";
		switch($value['type']) {
			case 1:
				echo $st_lang['categories_expense'];
				break;
			case 2:
				echo $st_lang['categories_income'];
				break;
			case 3:
				echo $st_lang['categories_both'];
				break;
		}
		echo "</span></li>";
	}
}
?>
</ul>
</div>
<br><br>

<script>
    $(document).ready(function() {
        $('#categories_list').sortable({
            delay: 100,
            stop:  function (event, ui) {
                // get all inputs inside categories_list and send
                var cats = {};
                $('#categories_list').find('input').each(function(index) {
                    cats[index] = $(this).attr('name');
                });
                $.post('/categories/order', cats);
            }
        });
    });
</script>