<div id="favourites_table" class="form-group accordion-body collapse">
    <table class="table table-striped table-bordered table-condensed table-hover" id="mytable" width="100%">
<?php
global $st_lang;
if(isset($this->favourites_list)) {
    ?>
    <thead>
    <tr>
        <th class="list moxie_edit">&nbsp;</th>
        <th class="list moxie_note"><?php echo $st_lang['expenses_note']; ?></th>
        <th class="list moxie_note"><?php echo $st_lang['tags_title']; ?></th>
    </tr>
    </thead>
    <?php
    foreach ($this->favourites_list as $key=>$value) {
        echo '
<tr>
<td class="list moxie_edit">
    <a class="moxieedit" href="/expenses/edit/id/'.$value['id'].'"><div class="moxieicon moxieedit"></div></a>
</td>
<td class="list moxie_note">'.$value['note'].'</td><td>';

        foreach($value['tags'] as $tagvalue) {
            echo $tagvalue." ";
        }
        echo '</td></tr>';
    }
}
?>
</table>
</div>