<table width="100%" cellspacing="20">
<tr>
<td valign=top>
<?php
echo $this->partial('categories/categories.phtml',
		array('categories'=>$this->categories, 'categories_list' => $this->categories_list, 'categories_form' => $this->categories_form));
?>
</td>
<td valign=top>
<?php
echo $this->partial('categories/budget.phtml',
					array('categories'=>$this->categories, 'budgets' => $this->st_budgetsList));
?>
</td>
</tr>
</table>
