<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?php global $st_lang; echo $st_lang['categories']; ?></title>
</head>
<body>
    <h1><?php echo $st_lang['categories_and_budget']; ?></h1>
    
<table width="100%" cellspacing="20">
<tr>
<td valign=top>
<?php
echo '<h2>'.$st_lang['categories'].'</h2>';
echo $this->form;

foreach ($this->list as $key => $value) {
	if (!empty($value['parent1'])) {
		$first_name = (!empty($value['name1'])) ? $value['name1']." --- " : "";
		echo '<a href="/categories/delete/id/'.$value['id1'].'" alt="Borrar" title="Borrar">X</a>&nbsp;';
		echo '<a href="/categories/edit/id/'.$value['id1'].'" alt="Editar" title="Editar">E</a>&nbsp;&nbsp;&nbsp;';
		echo $first_name.$value['name2']."<br>";
	}
}
?>
</td>
<td valign=top>
<?php
echo $this->partial('categories/budget.phtml',
					array('categories'=>$this->categories));
?>
</td>
</tr>
</table>
</body>
</html>
