<?php
function print_yearly_loop($yearly, $categories, $init_year) {
	$totals = array();
	foreach($categories as $key => $cat) {
		echo "<td style='text-align:left;'>".$cat."</td>";
		for ($i = $init_year; $i <= date('Y'); $i++) {
			if(!isset($totals[$i])) {
				$totals[$i] = 0;
			}
			$found = false;
			foreach($yearly[$i] as $data) {
				if($data['category'] == $key) {
					echo "<td>".$data['sum(amount)']." &euro;</td>";
					$totals[$i] += $data['sum(amount)'];
					$found = true;
					break;
				}
			}
			if(!$found) {
				echo "<td>0.00 &euro;</td>";
			}
		}
		echo "<tr>";
	}
	echo "<th style='text-align:left;'>TOTAL</th>";
	for($i = $init_year; $i <= date('Y'); $i++) {
		echo "<th>" . number_format($totals[$i], 2) . " &euro;</th>";
	}
	echo "</tr>";
	return $totals;
}

function print_yearly($yearly, $categories) {
	$keys = array_keys($yearly);
	$init_year = $keys[0];
	?>
	<div id="stats_table_yearly" class="collapse">
	<table class="table table-striped table-bordered table-stats">
	<th style='width: 200px'></th>
	<?php
	for($i = $init_year; $i <= date('Y'); $i++) {
		echo "<th style='text-align:right;'	>".$i."</th>";
	}
	echo "</tr>";
	print_yearly_loop($yearly, $categories, $init_year);
	echo "</table></div>";
}
?>

<style type="text/css">
table.table-stats {
	font-size: 11px;
	width: 100%;
}
.table-stats td, th {
	text-align: right;
}
</style>
<script type="text/javascript" src="/js/stats/stats.js"></script>
<script type="text/javascript">
	var budgets = [];
<?php
global $st_lang;

$s_budget = "";
$s_categories = array();
foreach ($this->budget as $key => $value) {
	$s_budget .= "budgets[".$key."] = new Array();\n";
	foreach ($value as $inner_key => $inner_value) {
		$s_budget .= "budgets[".$key."][".$inner_key."] = ".$inner_value.";\n";
		if(!in_array($inner_key, $s_categories)) {
			$s_categories[] = $inner_key;
		}
	}
}
echo $s_budget;

?>
var categories = [<?php echo implode(',', $s_categories);?>];
var budget_index = <?php echo date('m'); ?>;
</script>

<button data-toggle="collapse" data-target="#budget" class="btn btn-info"><?php echo $st_lang['stats_budget_title']; ?></button>
<button data-toggle="collapse" data-target="#stats_table_yearly" class="btn btn-info">Anual</button>
<button data-toggle="collapse" data-target="#stats_trends_container" class="btn btn-info"><?php echo $st_lang['stats_trends']; ?></button>
<button data-toggle="collapse" data-target="#box" class="btn btn-info"><?php echo $st_lang['stats_title']; ?></button>
<div id="budget" class="accordion-body">
<table width=100%>
	<!-- Form + expenses list -->
	<tr>
	<td>
		<?php
		global $st_lang;
		$last_url = '/stats/index/year/'.($this->year-1);
		$next_url = '/stats/index/year/'.($this->year+1);
		$current_month_and_year = $this->year;
		$this->getHelper('Web')->printHeaderNextLastInterval($last_url, $next_url, $current_month_and_year);
		?>

	</td>
	</tr>
</table>

<table class="table table-striped table-bordered table-stats table-condensed table-hover">
<th></th>
<?php
$income = array();
$expense = array();
$incomes_as_budget = array();
$balance = 0;
$table_headers = '';
for ($month = 1; $month <= 12; $month++) {
	$income[$month] = 0;
	$expense[$month] = 0;
	$table_headers .= '<th><a href="/expenses/index/month/'.$month.'/year/'.$this->year.'">'.date('M',mktime(1,1,1,$month,1,$this->year)).'</a></th>';
}
echo $table_headers;
if (!empty($this->budget)) {
	echo '<th><a href="/categories/index">'.$st_lang['budget'].'</a></th>';
	$i_colspan = 14;
}
else {
	$i_colspan = 13;
}
echo '<tr>';
$incomes = '';
foreach ($this->budget_incomes as $key => $category) {
	$incomes .= '<td style="text-align:left;">'.$category.'</td>';
	for ($month = 1; $month <= 12; $month++) {
		$current_income = 0;
		foreach ($this->incomes[$month] as $income_key => $value) {
			if ($value['category'] == $key) {
				$current_income += $value['amount'];
				$incomes_as_budget[$key] += $value['amount'];
			}
		}
		$income[$month] += $current_income;

		$incomes .= '<td><a style="color: #000000" href="/incomes/index/category/'.$key.'/month/'.$month.'/year/'.$this->year.'"> '.number_format($current_income,2).' &euro;</a></td>';
	}
	if (!empty($this->budget)) {
		$incomes .= '<td>'.number_format($incomes_as_budget[$key],2).' &euro;</td>';
	}
	$incomes .= '<tr>';
}
echo $incomes;

echo '<th style="text-align:left;">'.$st_lang['stats_budget_income'].'</th>';
$incomes_totals = '';
for ($month = 1; $month <= 12; $month++) {
	$incomes_totals .= '<th align="right">'.number_format($income[$month],2).' &euro;</th>';
}
echo $incomes_totals;
if (!empty($this->budget)) echo '<th></th>';
echo '<tr>';
echo '<td colspan='.$i_colspan.'>&nbsp;</td><tr>';

$expenses = '';
foreach ($this->budget_expenses as $key => $category) {
	$expenses .= '<td style="text-align:left;">'.$category.'</td>';
	for ($month = 1; $month <= 12; $month++) {
		$current_expense = 0;
		foreach ($this->expenses[$month] as $expense_key => $value) {
			if ($value['category'] == $key) $current_expense += $value['amount'];
		}
		$expense[$month] += $current_expense;
		if (!empty($this->budget)) {
			if (!isset($this->budget[$month][$key])) {
				// search for this key in forward months
				for ($i = $month+1; $i < 13; $i++) {
					if (isset($this->budget[$i][$key]))
						$this->budget[$month][$key] = $this->budget[$i][$key];
				}
				// if still unset...
				if (!isset($this->budget[$month][$key]))
					$this->budget[$month][$key] = $current_expense;
			}
			$s_color = ($current_expense > $this->budget[$month][$key]) ?
				' style="color: #FF0000"' : ' style="color: #000000"';
		}
		else {
			$s_color = '';
		}
		$expenses .= '<td name="month'.$month.'"><a '.$s_color.' href="/expenses/index/category/'.$key.'/month/'.$month.'/year/'.$this->year.'">'.number_format($current_expense,2).' &euro;</a></td>';
	}
	if (!empty($this->budget)) {
		$i_budget = (!empty($this->budget[date('m')][$key])) ? $this->budget[date('m')][$key] : 0;
		$expenses .= '<td style="color: #00FF00" id="budget'.$key.'">'.number_format($i_budget,2).' &euro;</td>';
	}
	$expenses .= '<tr>';
}
echo $expenses;
echo '<th style="text-align:left;">'.$st_lang['stats_budget_expense'].'</th>';
$totals = '';
$balance_output = '';
for ($month = 1; $month <= 12; $month++) {
	$totals .= '<th align="right">';
	$totals .= '<a href="/expenses/index/month/'.$month.'/year/'.$this->year.'">';
	$totals .= number_format($expense[$month],2);
	$totals .= ' &euro;</a></th>';

	$monthTotal = $income[$month]-$expense[$month];
	$style = $monthTotal < 0 ? "color: #ff0000" : "";
	$balance_output .= '<th align="right"><span style="'.$style.'">'.number_format(($monthTotal),2).' &euro;</span></th>';
	$balance += ($income[$month]-$expense[$month]);
}
$balance_style = $balance < 0 ? "color: #ff0000" : "";
echo $totals;
if (!empty($this->budget)) echo '<th></th>';
?>
<tr>
<td colspan='.$i_colspan.'>&nbsp;</td><tr>

<th style="text-align:left;"><?php echo $st_lang['stats_budget_total']; ?></th>
<?php echo $balance_output; ?>

<th align="right"><span style="'.$style.'"><?php echo number_format($balance,2); ?> &euro;</span></th>
</tr>
</table>
</div>

<?php
print_yearly($this->yearly, $this->budget_incomes + $this->budget_expenses);

echo $this->partial('stats/stats.phtml', array('trends'=>$this->trends));
?>
<div id="box" class="accordion-body collapse">
<table width=100% class="table table-striped table-bordered table-stats">
<tr>
<th align="left"><?= $st_lang['category']; ?></th>
<th align="right"><?= $st_lang['total']; ?></th>
<th align="right"><?= $st_lang['total_this_year']; ?></th>
<th align="right"><?= $st_lang['average_this_year']; ?></th>
<th align="right"><?= $st_lang['average_unit']; ?></th>
</tr>
<?php
$i_currentMonth = date('m');
foreach ($this->data as $key => $value) {
	echo '<tr>
	<td>'.$value['name'].'</td>
	<td align="right">'.number_format($value['sumtotal'],2).' &euro;</td>
	<td align="right">'.number_format($value['sumyear'],2).' &euro;</td>
	<td align="right">'.number_format($value['sumyear']/$i_currentMonth,2).' &euro;</td>
	<td align="right">'.abs(number_format($value['avgyear'],2)).' &euro;</td>
	</tr>';
}
?>
</table>
</div>
