<link rel="stylesheet" type="text/css" href="/material.css"/>
<script type="text/javascript" src="/js/stats/stats.js"></script>
<script type="text/javascript">
<?php
global $st_lang;

$s_budget = "var budgets = new Array();\n";
$s_categories = array();
foreach ($this->budget as $key => $value) {
	$s_budget .= "budgets[".$key."] = new Array();\n";
	foreach ($value as $inner_key => $inner_value) {
		$s_budget .= "budgets[".$key."][".$inner_key."] = ".$inner_value.";\n";
		if(!in_array($inner_key, $s_categories)) {
			$s_categories[] = $inner_key;
		}
	}
}
echo $s_budget;

?>
var categories = [<?php echo implode(',', $s_categories);?>];
var budget_index = <?php echo date('m'); ?>;
</script>

<h2>
	<span id="show_budget">
		<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
			<i class="material-icons" style="background-color: ##0b77b7">+</i>
		</button>
		<span><?php echo $st_lang['stats_budget_title']; ?></span>
	</span>
</h2>
<br>
<div id="budget">
<table width=100%>
	<!-- Form + expenses list -->
	<tr>
	<td>
		<?php
		global $st_lang;
		$slugPreviousYear = '/stats/index/year/'.($this->year-1);
		$slugNextYear = '/stats/index/year/'.($this->year+1);
		?>
		<table width="100%">
			<td><a href="<?php echo $slugPreviousYear; ?>"><div class="moxieicon moxieprevious"></div> <span class="moxieprevious"><?php echo $st_lang['incomes_last_year']; ?></span></a></td>
			<td align="center"><span class="moxie_header_date"><?php echo $this->year; ?></span></td>
			<td align="right"><a href="<?php echo $slugNextYear; ?>"><div class="moxieicon moxienext"></div> <span class="moxienext"><?php echo $st_lang['incomes_next_year']; ?></span></a></td>
		</table>
	</td>
	</tr>
</table>
<br><br>

<table width=100% style="font-size: 11px;">
<th></th>
<?php
$income = array();
$expense = array();
$balance = 0;
for ($month = 1; $month <= 12; $month++) {
	$income[$month] = 0;
	$expense[$month] = 0;
	echo '<th align="right"><a href="/expenses/index/month/'.$month.'/year/'.date('Y').'">'.date('M',mktime(1,1,1,$month,1,date('Y'))).'</a></th>';
}
if (!empty($this->budget)) {
	echo '<th align="right"><a href="/categories/index">'.$st_lang['budget'].'</a></th>';
	$i_colspan = 14;
}
else {
	$i_colspan = 13;
}
echo '<tr>';
foreach ($this->budget_incomes as $key => $category) {
	echo '<td>'.$category.'</td>';
	for ($month = 1; $month <= 12; $month++) {
		$current_income = 0;
		foreach ($this->incomes[$month] as $income_key => $value) {
			if ($value['category'] == $key) $current_income += $value['amount'];
		}
		$income[$month] += $current_income;
		echo '<td align="right">'.number_format($current_income,2).' &euro;</td>';
	}
	if (!empty($this->budget)) echo '<td></td>';
	echo '<tr>';
}
echo '<th align="left">'.$st_lang['stats_budget_income'].'</th>';
for ($month = 1; $month <= 12; $month++) {
	echo '<th align="right">'.number_format($income[$month],2).' &euro;</th>';
}
if (!empty($this->budget)) echo '<th></th>';
echo '<tr>';
echo '<td colspan='.$i_colspan.'>&nbsp;</td><tr>';

foreach ($this->budget_expenses as $key => $category) {
	echo '<td>'.$category.'</td>';
	for ($month = 1; $month <= 12; $month++) {
		$current_expense = 0;
		foreach ($this->expenses[$month] as $expense_key => $value) {
			if ($value['category'] == $key) $current_expense += $value['amount'];
		}
		$expense[$month] += $current_expense;
		if (!empty($this->budget)) {
			if (!isset($this->budget[$month][$key])) {
				// search for this key in forward months
				for ($i = $month+1; $i < 13; $i++) {
					if (isset($this->budget[$i][$key]))
						$this->budget[$month][$key] = $this->budget[$i][$key];
				}
				// if still unset...
				if (!isset($this->budget[$month][$key]))
					$this->budget[$month][$key] = $current_expense;
			}
			$s_color = ($current_expense > $this->budget[$month][$key]) ?
				' style="color: #FF0000"' : ' style="color: #000000"';
		}
		else {
			$s_color = '';
		}
		echo '<td align="right"'.$s_color.' name="month'.$month.'">'.number_format($current_expense,2).' &euro;</td>';
	}
	if (!empty($this->budget)) {
		$i_budget = (!empty($this->budget[date('m')][$key])) ? $this->budget[date('m')][$key] : 0;
		echo '<td align="right" style="color: #00FF00" id="budget'.$key.'">'.number_format($i_budget,2).' &euro;</td>';
	}
	echo '<tr>';
}
echo '<th align="left">'.$st_lang['stats_budget_expense'].'</th>';
for ($month = 1; $month <= 12; $month++) {
	echo '<th align="right">';
	echo '<a href="/expenses/index/month/'.$month.'/year/'.date('Y').'">';
	echo number_format($expense[$month],2);
	echo ' &euro;</a></th>';
}
if (!empty($this->budget)) echo '<th></th>';
echo '<tr>';
echo '<td colspan='.$i_colspan.'>&nbsp;</td><tr>';

echo '<th align="left">'.$st_lang['stats_budget_total'].'</th>';
for ($month = 1; $month <= 12; $month++) {
	echo '<th align="right">'.number_format(($income[$month]-$expense[$month]),2).' &euro;</th>';
	$balance += ($income[$month]-$expense[$month]);
}
echo '<th align="right">'.number_format($balance,2).' &euro;</th>
</tr>';
?>
</table>
</div>
<br><br>
<h2>
	<span id="show_stats">
		<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
			<i class="material-icons">+</i>
		</button>
		<?php echo $st_lang['stats_title']; ?>
	</span>
</h2>
<br>
<div id="box">
<table width=100%>
<tr>
<th align="left"><?= $st_lang['category']; ?></th>
<th align="right"><?= $st_lang['total']; ?></th>
<th align="right"><?= $st_lang['total_this_year']; ?></th>
<th align="right"><?= $st_lang['average_this_year']; ?></th>
<th align="right"><?= $st_lang['average_unit']; ?></th>
</tr>
<?php
foreach ($this->data as $key => $value) {
	$i_currentMonth = date('m');
	echo '<tr>
	<td>'.$value['name'].'</td>
	<td align="right">'.number_format($value['sumtotal'],2).' &euro;</td>
	<td align="right">'.number_format($value['sumyear'],2).' &euro;</td>
	<td align="right">'.number_format($value['sumyear']/$i_currentMonth,2).' &euro;</td>
	<td align="right">'.number_format($value['avgyear'],2).' &euro;</td>
	</tr>';
}
?>
</table>
</div>
