<!-- Graphic -->
<link rel="stylesheet" type="text/css" href="/css/trends.css"/>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
	var moxie_url = "<?php echo Zend_Registry::get('config')->moxie->settings->url; ?>";

	var trends_array = [];
	<?php
	$default = null;
	foreach($this->trends as $key=>$value) {
		if(empty($default))
			$default = $key;
		$category_name = $value['name'];
		?>
	trends_array[<?php echo $key; ?>] = [
		['Mes/año', '<?php echo $category_name;?>'],
		<?php
		foreach($value['data'] as $data_key => $data_value) {
			echo "['".$data_value['month']."/".$data_value['year']."', ".$data_value['amount']."],";
		}
		?>
	];
	<?php
	}
	?>
	var default_category = <?php echo $default; ?>
</script>
<script type="text/javascript" src="/js/stats/trends.js"></script>

<div id="stats_trends_container">
<div id="stats_trends"></div>
<label for="trends_category"></label>
<select id="trends_category" name="trends_category" onchange="drawChart();" class="form-control">
	<?php
	foreach($this->trends as $key => $value) {
		echo '<option value="'.$key.'">'.$value['name'].'</option>';
	}
	?>
</select>
</div>