<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Moxie</title>
</head>
<body>
<?php
include '/html/web.php';
echo web_header(Zend_Registry::get('config')->moxie->app->name,
		Zend_Registry::get('config')->moxie->settings->url);
echo web_menu();
?>
Moxie es una aplicación que te permitirá controlar los gastos del hogar, tus ingresos, y elaborar
un presupuesto para el hogar. También podrás adaptar las categorías y subcategorías a tus propias
necesidades.<br>
Si el Excel o las hojas de cálculo se te han quedado pequeñas o si nunca has realizado estas tareas,
esta aplicación puede ayudarte a llevar un control mejor sobre la economía de tu hogar. Si tienes
un pequeño negocio y necesitas llevar las cuentas pero no te hace falta ningun software sofisticado,
también te puede ayudar.<br>
<br>
<br>
<table width="100%">
<td valign="top">
Lecturas recomendadas:<br>
<a href="http://www.elblogsalmon.com/economia-domestica/cual-es-tu-presupuesto-familiar">¿Cuál es tu presupuesto familiar?</a><br>
<a href="http://comoahorrardinero.com/como-hacer-un-presupuesto">¿Cómo hacer un presupuesto?</a><br>
<a href="http://dineroexperto.com/blog/%C2%BFcomo-cuidar-el-dinero/">¿Cómo cuidar el dinero?</a><br>
</td>
<td align="right" rowspan=2>
<!-- Follow me on Twitter -->
<!-- Last tweet -->
<script src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 1,
  interval: 12000,
  width: 260,
  height: 300,
  theme: {
    shell: {
      background: '#ffffff',
      color: '#0b78b7'
    },
    tweets: {
      background: '#ffffff',
      color: '#0b78b7',
      links: '#0b78b7'
    }
  },
  features: {
    scrollbar: false,
    loop: true,
    live: false,
    hashtags: true,
    timestamp: true,
    avatars: false,
    behavior: 'default'
  }
}).render().setUser('___moxie___').start();
</script>
<iframe allowtransparency="true" frameborder="0" scrolling="no"
  src="http://platform.twitter.com/widgets/follow_button.html?screen_name=___moxie___"
  style="width:250px; height:20px;"></iframe>
</td><tr>
<td>
<br><br>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="RVPQ896TDVARA">
<input type="image" src="https://www.paypalobjects.com/es_ES/ES/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal. La forma rápida y segura de pagar en Internet.">
<img alt="" border="0" src="https://www.paypalobjects.com/es_ES/i/scr/pixel.gif" width="1" height="1">
</form>
</td>
</table>
</body>
</html>