<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/finances/utils.js"></script>
<script type="text/javascript">
var check = function() {
    if($('#amount').val() != ""
        && $('#rate').val() != ""
        && $('#months').val() != "") {
        finances = new Finances();
        finances.finalCapital($('#amount').val(), $('#rate').val(), $('#months').val());
        $('#interest').val(finances.interest);
        $('#total').val(finances.getTotal());
    }
}

$(document).ready(function() {
    $('#amount').change(check);
    $('#rate').change(check);
    $('#months').change(check);
});

</script>

<h2>Calculadora de dep&oacute;sitos</h2>
<form class="moxie_form">
<?php global $st_lang; ?>
    <div>
    <dt for="amount"><?php echo $st_lang['finances_amount']; ?></dt>
    <dd><input id="amount" type="number" placeholder="0,00"></dd>
    </div>
    <div>
    <dt for="rate"><?php echo $st_lang['finances_interest']; ?></dt>
    <dd><input id="rate" type="number" placeholder="0"></dd>
    </div>
    <div>
    <dt for="months"><?php echo $st_lang['finances_period']; ?></dt>
    <dd><input id="months" type="number" placeholder="12"></dd>
    </div>
    <div>
    <dt for="interest"><?php echo $st_lang['finances_revenue']; ?></dt>
    <dd><input id="interest"></dd>
    </div>
    <div>
    <dt for="total"><?php echo $st_lang['finances_total']; ?></dt>
    <dd><input id="total"></dd>
    </div>
</form>
<div height=20px>&nbsp;</div>
