<script type="text/javascript">
<?php
global $st_lang;

$s_budget = "var budgets = new Array();\n";
$s_categories = array();
foreach ($this->budget as $key => $value) {
	$s_budget .= "budgets[".$key."] = new Array();\n";
	foreach ($value as $inner_key => $inner_value) {
		$s_budget .= "budgets[".$key."][".$inner_key."] = ".$inner_value.";\n";
		if(!in_array($inner_key, $s_categories)) {
			$s_categories[] = $inner_key;
		}
	}
}
echo $s_budget;

?>
var categories = [<?php echo implode(',', $s_categories);?>];
function onmouseoverchange(month) {
	for (category in categories) {
		$("#budget"+category).html((budgets[month][categories[category]].toFixed(2))+" &euro;");
	}
}

function onmouseoutchange() {
	for (category in categories) {
		$("#budget"+category).html((budgets[<?php echo date('m'); ?>][categories[category]].toFixed(2))+" &euro;");
	}
}

$(document).ready(function() {
    $("#show_stats").click(
		function(event) {
    		$("#box").slideToggle();
		}
	);
    $("#show_budget").click(
    		function(event) {
        		$("#budget").slideToggle();
    		}
    	);
	$("#caja").click(function(event) {
	    $("#box").slideUp();
	});
	$("[name^='month']").mouseover(function() {
		var monthId = $(this).attr('name').replace('month', '');
		onmouseoverchange(monthId);
	});
	$("[name^='month']").mouseout(function() {
		var monthId = $(this).attr('name').replace('month', '');
		onmouseoutchange(monthId);
	});
});

</script>

<h2>Selecciona un tipo de depósito</h2>
<div></div>