<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/finances/utils.js"></script>
<script type="text/javascript">
var check = function() {
    if($('#amount').val() != 0
        && $('#rate').val() != 0
        && $('#months').val() != 0) {
        finances = new Finances();
        finances.finalCapital($('#amount').val(), $('#rate').val(), $('#months').val());
        $('#interest').val(finances.interest);
        $('#total').val(finances.getTotal());
    }
}

$(document).ready(function() {
    $('#amount').change(check);
    $('#rate').change(check);
    $('#months').change(check);
});

</script>

<h2>Selecciona un tipo de depósito</h2>
<form>
<?php global $st_lang; ?>
    <div>
    <label for="amount"><?php echo $st_lang['finances_amount']; ?></label>
    <input id="amount" type="number" value="0" placeholder="0,00">
    </div>
    <div>
    <label for="rate"><?php echo $st_lang['finances_interest']; ?></label>
    <input id="rate" type="number" value="0" placeholder="0">
    </div>
    <div>
    <label for="months"><?php echo $st_lang['finances_period']; ?></label>
    <input id="months" type="number" value="0" placeholder="12">
    </div>
    <div>
    <label for="interest"><?php echo $st_lang['finances_revenue']; ?></label>
    <input id="interest">
    </div>
    <div>
    <label for="total"><?php echo $st_lang['finances_total']; ?></label>
    <input id="total">
    </div>
</form>
<div></div>
