<table class="list moxie moxie-data" style="width: 100%" id="mytable">
<tr>
<td colspan=4 align=right>
Filtrar por <select id="category_filter" onchange="filter();">
<option value="0">---</option>
<?php
foreach ($this->form->getElement('category') as $key => $value) {
	if ($key == "options") {
		foreach ($value as $key2 => $value2) {
			echo '<option value="'.$key2.'">'.$value2.'</option>';
		}
	}
}
?>
</select>
</td>
</tr>
<?php
$f_totalAmount = 0;
$f_currentAmount = 0;
$b_showTotalAmount = false;
foreach ($this->list as $key=>$value) {
	$checked = ($value['in_sum'] == '1') ? "checked":"";
	$s_dateGet = (isset($this->month) && isset($this->year)) ? '/year/'.$this->year.'/month/'.$this->month : '';
	$expense_date = date('d-m-Y', strtotime($value['date']));
	
	echo '
<tr id="tr'.$value['id'].'">
<td class="list moxie_edit"><a class="moxieedit" href="'.$this->editSlug.$value['id'].$s_dateGet.'"><div class="moxieicon moxieedit"></div></a></td>
<td class="list moxie_category"><div alt="'.$value['description'].'" title="'.$value['description'].'">'.$value['name'].'</div></td>
<td class="list moxie_note"><span alt="'.$expense_date.'" title="'.$expense_date.'">'.$value['note'].'</span></td>
<td align="right" class="list moxie_amount"><span id="val'.$value['id'].'">'.number_format($value['amount'],2).' &euro;</span></td>
</tr>';

	$f_totalAmount = $f_totalAmount + $value['amount'];
	$f_currentAmount += ($value['in_sum'] == 1) ? $value['amount'] : 0;
	$b_showTotalAmount = ($value['in_sum'] != 1) || $b_showTotalAmount;
}

$s_total = number_format($f_currentAmount,2)." &euro;";
if($b_showTotalAmount) {
	$s_total .= '<br><span class="total_amount">'.number_format($f_totalAmount, 2)." &euro;";
}

?>
<tr>
<td colspan=4 align="right" class="list list_money"><span id="total"><?php echo $s_total; ?></span></td>
</tr>
</table>
<br><br><br>
