<table class="list moxie moxie-data" style="width: 100%" id="mytable">
<tr>
<td colspan=5><button class="moxiebutton" id="export_to_excel_button" value="Exportar" onclick="export_to_excel()">Exportar</button></td>
</tr>
<?php
$f_totalAmount = 0;
$f_currentAmount = 0;
$b_showTotalAmount = false;
$s_currentExpenseDate = '';
foreach ($this->list as $key=>$value) {
	$checked = ($value['in_sum'] == '1') ? "checked":"";
	$checked_style = ($value['in_sum'] == '0') ? "total_amount" : "";
	$s_dateGet = (isset($this->month) && isset($this->year)) ? '/year/'.$this->year.'/month/'.$this->month : '';
	$expense_date = date('d-m-Y', strtotime($value['date']));
	if($expense_date != $s_currentExpenseDate) {
		echo '<tr><th colspan="5" class="list_moxie_top" style="padding-top: 8px;">'.$expense_date.'</th></tr>';
		$s_currentExpenseDate = $expense_date;
	}
	
	echo '
<tr id="tr'.$value['id'].'">
<td class="list moxie_edit '.$checked_style.'"><a class="moxieedit" href="'.$this->editSlug.$value['id'].$s_dateGet.'"><div class="moxieicon moxieedit"></div></a></td>
<td class="list moxie_category '.$checked_style.'"><div alt="'.$value['description'].'" title="'.$value['description'].'">'.$value['name'].'</div></td>
<td class="list moxie_note '.$checked_style.'">'.$value['note'].'</td>
<td class="list moxie_date_inline '.$checked_style.'">'.$expense_date.'</td>
<td align="right" class="list moxie_amount '.$checked_style.'"><span id="val'.$value['id'].'">'.number_format($value['amount'],2).' &euro;</span></td>
</tr>';

	$f_totalAmount = $f_totalAmount + $value['amount'];
	$f_currentAmount += ($value['in_sum'] == 1) ? $value['amount'] : 0;
	$b_showTotalAmount = ($value['in_sum'] != 1) || $b_showTotalAmount;
}

$s_total = number_format($f_currentAmount,2)." &euro;";
if($b_showTotalAmount) {
	$s_total .= '<br><span class="total_amount">'.number_format($f_totalAmount, 2)." &euro;";
}

?>
<tr>
<td colspan=5 align="right" class="list list_money"><span id="total"><?php echo $s_total; ?></span></td>
</tr>
</table>
<?php $this->getHelper('Web')->printToTop(); ?>
<br><br><br>