<?php
global $st_lang;
if($this->source == "expenses") {
    $last_month = ($this->month == 1) ? 12 : $this->month - 1;
    $last_year = ($this->month == 1) ? $this->year - 1 : $this->year;
    $next_month = ($this->month == 12) ? 1 : $this->month + 1;
    $next_year = ($this->month == 12) ? $this->year + 1 : $this->year;
    $last_url = "/expenses/index/month/" . $last_month . "/year/" . $last_year;
    $next_url = "/expenses/index/month/" . $next_month . "/year/" . $next_year;
    $current_month_and_year = date("M Y", strtotime("01-" . $this->month . "-" . $this->year));
}
else {
    $editSlug = '/incomes/edit/id/';
    $current_month_and_year = date("Y", strtotime("01-01-".$this->year));
    $last_url = "/incomes/index/year/".($this->year-1);
    $next_url = "/incomes/index/year/".($this->year+1);

}
?>
<table class="table table-striped table-bordered table-condensed table-hover" id="mytable" width="100%">
<thead>
    <tr>
        <td colspan="5">
        <?php
        if($this->source == "expenses") {
            $this->getHelper('Web')->printHeaderNextLastInterval($last_url, $next_url, $current_month_and_year);
        }
        else {
            $this->getHelper('Web')->printHeaderNextLastInterval($last_url, $next_url, $current_month_and_year);
        }
        ?>
        </td>
    </tr>
	<tr>
		<td class="list moxie_edit">&nbsp;</td>
		<td class="list moxie_category"><?php echo $st_lang['expenses_category']; ?></td>
		<td class="list moxie_note"><?php echo $st_lang['expenses_note']; ?></td>
	<?php
	if ($this->view) {
		$target = '/'.$this->view.'/index';
		if ($this->month) {
			$target .= '/month/'.$this->month;
		}
		if ($this->year) {
			$target .= '/year/'.$this->year;
		}
		$date_filter = (strpos($this->o, 'date') !== false) ? "/o/".$this->o : "/o/date";
		$amount_filter = (strpos($this->o, 'amount') !== false) ? "/o/".$this->o : "/o/amount";
	?>
		<td align="center" class="list moxie_date_inline sorting"><a href="<?php echo $target . $date_filter; ?>"><?php echo $st_lang['expenses_date']; ?></a></td>
		<td align="right" class="list moxie_amount sorting"><a href="<?php echo $target . $amount_filter; ?>"><?php echo $st_lang['expenses_amount']; ?></a></td>
	<?php } else { ?>
		<td align="center" class="list moxie_date_inline sorting"><?php echo $st_lang['expenses_date']; ?></td>
		<td align="right" class="list moxie_amount sorting"><?php echo $st_lang['expenses_amount']; ?></td>
	<?php } ?>
	</tr>
	</thead>
<?php
$f_totalAmount = 0;
$f_currentAmount = 0;
$b_showTotalAmount = false;
$s_currentExpenseDate = '';
foreach ($this->list as $key=>$value) {
	$checked = ($value['in_sum'] == '1') ? "checked":"";
	$checked_style = ($value['in_sum'] == '0') ? "total_amount" : "";
	$s_dateGet = (isset($this->month) && isset($this->year)) ? '/year/'.$this->year.'/month/'.$this->month : '';
	$expense_date = date('d-m-Y', strtotime($value['date']));
	if($expense_date != $s_currentExpenseDate) {
		echo '<tr><th colspan="5" class="list_moxie_top" style="padding-top: 8px;">'.$expense_date.'</th></tr>';
		$s_currentExpenseDate = $expense_date;
	}
	
	echo '
<tr id="tr'.$value['id'].'">
<td class="list moxie_edit '.$checked_style.'"><a class="moxieedit" href="'.$this->editSlug.$value['id'].$s_dateGet.'"><div class="moxieicon moxieedit"></div></a></td>
<td class="list moxie_category '.$checked_style.'"><div alt="'.$value['description'].'" title="'.$value['description'].'">'.$value['name'].'</div></td>
<td class="list moxie_note '.$checked_style.'">'.$value['note'].'</td>
<td class="list moxie_date_inline '.$checked_style.'">'.$expense_date.'</td>
<td align="right" class="list moxie_amount '.$checked_style.'"><span id="val'.$value['id'].'">'.number_format($value['amount'],2).' &euro;</span></td>
</tr>';

	$f_totalAmount = $f_totalAmount + $value['amount'];
	$f_currentAmount += ($value['in_sum'] == 1) ? $value['amount'] : 0;
	$b_showTotalAmount = ($value['in_sum'] != 1) || $b_showTotalAmount;
}

$s_total = number_format($f_currentAmount,2)." &euro;";
if($b_showTotalAmount) {
	$s_total .= '<br><span class="total_amount">'.number_format($f_totalAmount, 2)." &euro;";
}

?>
<tr>
<td colspan=2><button class="btn btn-default btn-xs" id="export_to_excel_button" value="Exportar" onclick="export_to_excel()">Exportar</button></td>
<td colspan=3 align="right" class="list list_money"><span id="total"><?php echo $s_total; ?></span></td>
</tr>
</table>
<?php $this->getHelper('Web')->printToTop(); ?>
<br><br><br>
