<?php global $st_lang; ?>
<link rel="stylesheet" type="text/css" href="/material.css"/>
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/finance/utils.js"></script>
<script type="text/javascript">
var current_id = 1;
var current_comparison = 1;
var form_template = "";
var finance_add_txt = "<?php echo $st_lang['finance_add_row']; ?>";

var check = function() {
    if($('#amount').val() != ""
        && $('#rate').val() != ""
        && $('#months').val() != "") {
        finance = new Finance();
        finance.finalCapital($('#amount').val(), $('#rate').val(), $('#months').val());
        $('#interest').val(finance.interest);
        $('#total').val(finance.getTotal());
    }
}

function disableCurrentForm() {
    $('#moxie_form_'+current_id+" *").filter(":input").each(function(e) {
        $(this).attr('disabled', 'disabled');
        $(this).attr('id', $(this).attr('id')+current_id);
    });
    current_id++;
}

function getDepositForm() {
    return "<div id='moxie_form_"+current_id+"' style='float: left'>"+form_template+"</div>";
}

var addForm = function() {
    disableCurrentForm();
    $(getDepositForm()).insertBefore('#add_form');
    $('#amount').change(check);
    $('#rate').change(check);
    $('#months').change(check);
}

var compare = function() {
    disableCurrentForm();
    $('#add_form').remove();
    $("<div id='pepe"+current_comparison+"' style='display: flex'>"+getDepositForm()+"<div id='add_form' style='float: left'>"
    +"<button class='mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored'>"
    +"<i class='material-icons' style='background-color: #0b77b7'>+</i>"
    +"</button>"+finance_add_txt+"</div></div>").insertAfter('#compare');
    $('#amount').change(check);
    $('#rate').change(check);
    $('#months').change(check);
    $('#add_form').click(addForm);
    current_comparison++;
}

$(document).ready(function() {
    $('#amount').change(check);
    $('#rate').change(check);
    $('#months').change(check);

    $('#add_form').click(addForm);
    $('#compare').click(compare);

    form_template = $('.moxie_form').wrap('<p/>').parent().html();
});

</script>

<?php
echo $this->partial('finance/shared.phtml',
    array(

    ));
?>

<h2><?php echo $st_lang['finance_title']; ?></h2>
<div id="container">
    <div id="compare">
        <button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
            <i class="material-icons" style="background-color: ##0b77b7">+</i>
        </button>
        <?php echo $st_lang['finance_compare']; ?>
    </div>
    <div id="pepe" style="display: flex">
        <div id="moxie_form_1" style='float: left'>
            <form class="moxie_form">
                <div>
                    <dt for="name"><?php echo $st_lang['finance_name']; ?></dt>
                    <dd><input id="name" type="text" placeholder=""></dd>
                </div>
                <div>
                <dt for="amount"><?php echo $st_lang['finance_amount']; ?></dt>
                <dd><input id="amount" type="number" placeholder="0,00"></dd>
                </div>
                <div>
                <dt for="rate"><?php echo $st_lang['finance_interest']; ?></dt>
                <dd><input id="rate" type="number" placeholder="0"></dd>
                </div>
                <div>
                <dt for="months"><?php echo $st_lang['finance_period']; ?></dt>
                <dd><input id="months" type="number" placeholder="12"></dd>
                </div>
                <div>
                <dt for="interest"><?php echo $st_lang['finance_revenue']; ?></dt>
                <dd><input id="interest"></dd>
                </div>
                <div>
                <dt for="total"><?php echo $st_lang['finance_total']; ?></dt>
                <dd><input id="total"></dd>
                </div>
            </form>
        </div>
        <div id="add_form" style='float: left'>
            <button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
                <i class="material-icons" style="background-color: #0b77b7">+</i>
            </button>
            <?php echo $st_lang['finance_add_row']; ?>
        </div>
    </div>
</div>
<div height=20px>&nbsp;</div>
