<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?php global $st_lang; echo $st_lang['users']; ?></title>
</head>
<body>
    <h1><?php echo $st_lang['users']; ?></h1>
    
<table width="100%" cellspacing="20">
<tr>
<td valign=top>
<?php
echo $this->form;
?>
</td>
</table>
</body>
</html>
