<script type="text/javascript">
<?php global $st_lang; ?>

$(document).ready(function() {
	$("#myaccountform").submit(function(e){
		var error_message = "<?php echo $st_lang['myaccount_password_error']?>";
		if ($("#password").val() == $("#password_check").val()) {
			$("#myaccountform").submit();
		}
		else {
			alert(error_message);
			return false;
		}
	});

    $('.toggable ').each(function (e) {
        $(this).click(function(e) {
            $('.toggable').not(this).each(function(e) {
                var button = $(this);
                button.removeClass('btn-primary');
                button.addClass('btn-info');
                var collapse = button.attr('data-target');
                $(collapse).hide();
            });
            $(this).removeClass('btn-info');
            $(this).addClass('btn-primary');
            var collapse = $(this).attr('data-target');
            $(collapse).show();
        });
    });
});
</script>

<button data-target="#my_account" class="toggable btn btn-info"><?php echo $st_lang['users_my_account']; ?></button>
<button data-target="#categories_table" class="toggable btn btn-info"><?php echo $st_lang['categories']; ?></button>
<button data-target="#favourites_table" class="toggable btn btn-info"><?php echo $st_lang['favourites_message']; ?></button>
<button data-target="#budget_table" class="toggable btn btn-info"><?php echo $st_lang['budget']; ?></button>
<button data-target="#tags_table" class="toggable btn btn-info"><?php echo $st_lang['tags_title']; ?></button>

<div id="my_account" class="accordion-body collapse form-group">
    <?php
    echo $this->form;
    ?>
</div>

<?php
echo $this->partial('categories/categories.phtml',
		array('categories'=>$this->categories, 'categories_form' => $this->categories_form, 'categories_list' => $this->categories_list, 'categories_display' => $this->categories_display, 'categories_collapse' => $this->categories_collapse));

echo $this->partial('categories/favourites.phtml',
        array('favourites_list' => $this->favourites_list));

echo $this->partial('categories/budget.phtml',
		array('categories'=>$this->categories, 'budgets_list' => $this->budgets_list));

echo $this->partial('tags/tags.phtml',
        array('tag_list' => $this->tag_list));
?>

<div id="donate">
	<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
		<input type="hidden" name="cmd" value="_s-xclick">
		<input type="hidden" name="hosted_button_id" value="RVPQ896TDVARA">
		<input style="height: auto;" type="image" src="https://www.paypalobjects.com/es_ES/ES/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal. La forma rápida y segura de pagar en Internet.">
		<img alt="" border="0" src="https://www.paypalobjects.com/es_ES/i/scr/pixel.gif" width="1" height="1">
	</form>
</div>
