<link rel="stylesheet" type="text/css" href="/material.css"/>
<script type="text/javascript" src="/bower_components/material-design-lite/material.js"></script>
<script type="text/javascript">
<?php global $st_lang; ?>

$(document).ready(function() {
	$("#users_my_account").click(function (event) {
		$("#my_account").slideToggle();
	});
	$("#categories_title").click(function (event) {
		$("#categories_table").slideToggle();
	});
	$("#budget_title").click(function (event) {
		$("#budget_table").slideToggle();
	});
    $("#tags_title").click(function (event) {
        $("#tags_table").slideToggle();
    });
	$("#users_donate").click(function (event) {
		$("#donate").slideToggle();
	});

	$("#myaccountform").submit(function(e){
		var error_message = "<?php echo $st_lang['myaccount_password_error']?>";
		if ($("#password").val() == $("#password_check").val()) {
			$("#myaccountform").submit();
		}
		else {
			alert(error_message);
			return false;
		}
	});
});
</script>

<h1><?php echo $st_lang['users_title']; ?></h1>

<h2 id="users_my_account">
	<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
		<i class="material-icons" style="background-color: ##0b77b7">+</i>
	</button>
	<?php echo $st_lang['users_my_account']." ".$st_lang['press_here_display']; ?>
</h2>
<div id="my_account" style="display: none;">
<table width="100%" cellspacing="20">
<tr>
<td valign=top>
<?php
echo $this->form;
?>
</td>
</tr>
</table>
</div>
<br><br>

<?php
echo $this->partial('categories/categories.phtml',
		array('categories'=>$this->categories, 'categories_form' => $this->categories_form, 'categories_list' => $this->categories_list, 'categories_display' => $this->categories_display));

echo $this->partial('categories/budget.phtml',
		array('categories'=>$this->categories, 'budgets_list' => $this->budgets_list));

echo $this->partial('tags/tags.phtml',
        array('tag_list' => $this->tag_list));
?>

<h2 id="users_donate">
	<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
		<i class="material-icons" style="background-color: ##0b77b7">+</i>
	</button>
	<?php echo $st_lang['users_donate']." ".$st_lang['press_here_display']; ?>
</h2>
<div id="donate" style="display: none;">
	<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
		<input type="hidden" name="cmd" value="_s-xclick">
		<input type="hidden" name="hosted_button_id" value="RVPQ896TDVARA">
		<input style="height: auto;" type="image" src="https://www.paypalobjects.com/es_ES/ES/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal. La forma rápida y segura de pagar en Internet.">
		<img alt="" border="0" src="https://www.paypalobjects.com/es_ES/i/scr/pixel.gif" width="1" height="1">
	</form>
</div>
