<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Moxie</title>
<link rel="stylesheet" type="text/css" href="/node_modules/taggle/example/css/taggle.css">
<link rel="stylesheet" type="text/css" href="/moxie.css?v=3"/>
<link rel="stylesheet" href="/bower_components/chosen/chosen.css">
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/bower_components/jquery-ui/jquery-ui.min.js"></script>
<script type="text/javascript" src="/bower_components/chosen/chosen.jquery.js"></script>
<script type="text/javascript" src="/js/common.js"></script>
<script type="text/javascript" src="/node_modules/taggle/src/taggle.js"></script>
<link rel="stylesheet" type="text/css" href="/material.css"/>
<script type="text/javascript" src="/bower_components/material-design-lite/material.js"></script>

<link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap-theme.min.css">
<script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

<script type="text/javascript">

	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-10754954-7']);
	_gaq.push(['_trackPageview']);

	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();

</script>
</head>

<body>
<?php
echo $this->render('header.phtml');
echo $this->layout()->content;
echo $this->render('footer.phtml');
?>
</body>
</html>
