<header>
<table width=100%>
<tr>
<td valign="top" class="moxietitle" width="233" height="65" onclick="window.location='<?php echo Zend_Registry::get('config')->moxie->settings->url; ?>'"></td>
<td align="right" class="moxie_login_header">
<?php
global $st_lang;

$url = $_SERVER['REQUEST_URI'];
$st_url = explode("/", $url);
$st_urls = array(
    'categories' => '/categories/index',
    'incomes' => '/incomes/index',
    'expenses' => '/expenses/index',
    'stats' => '/stats/index',
    'finances' => '/finances/index',
    'users' => '/users/index'
);
$settingsUrl = Zend_Registry::get('config')->moxie->settings->url;

if (!isset($_SESSION['user_id']) || $_SESSION['user_id'] == 0) {
?>
        <form name="login" id="login" action="<?php echo Zend_Registry::get('config')->moxie->settings->url; ?>/login/login" method="POST">
        <fieldset class="login contact">
        <legend>Login</legend>
        <table width=200>
        <tr><td><label for="username">Login</label></td><td><input type="text" name="login" id="login" maxlenght=15></td></tr>
        <tr><td><label for="username">Password</label></td><td><input type="password" name="password" id="password" maxlenght=15></td></tr>
        <tr><td colspan=2 align="right"><input type="submit" value="Login"></td></tr>
        <tr><td colspan=2 align="right"><a href="/login/newuser"><?php echo $st_lang['new_user']; ?></a>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <a href="/login/forgotpassword"><?php echo $st_lang['forgot_password']; ?></a></td></tr>
        </table>
        </fieldset>
        </form>
<?php
}
else {
    ?>
    <nav>
        <ul>
        <?php
        echo '<li>'.$_SESSION['user_name'].'</li>';
        foreach($st_urls as $key => $value) {
            echo '<li><a href="'.$settingsUrl.$st_urls[$key].'">'.$st_lang[$key].'</a></li>';
        }
        ?>
        </ul>
    </nav>
    <?php
}
?>
</td>
</tr>
</table>
</header>
<!-- web menu -->
<?php
        $st_lang['users'] = $st_lang['users_my_account'];
        $style = 'style="display: inline-block; padding: 5px; border-radius: 5px; background-color: #D0E8F4; color: white; border 5px solid white;"';

        $s_webMenu = '
        <table cellspacing=10>
        ';
        if (isset($_SESSION['user_id'])) {
                $s_webMenu .= '
                <td>'.$_SESSION['user_name'].'</td>';

                foreach($st_urls as $key => $value) {
                        $s_webMenu .= '<td'.(($st_url[1] == $key) ? ' '.$style : '').'><a href="'.Zend_Registry::get('config')->moxie->settings->url.$st_urls[$key].'">'.$st_lang[$key].'</a></td>';
                }
                $s_webMenu .= '<td><a href="'.Zend_Registry::get('config')->moxie->settings->url.'/login/logout">'.$st_lang['logout'].'</a></td>
                ';
        }
        else {
                $s_webMenu .= '
                <td><a href="'.Zend_Registry::get('config')->moxie->settings->url.'/">'.$st_lang['index'].'</a></td>
                <td><a href="/finances/index">'.$st_lang['finances'].'</a></td>
                <td><a href="'.Zend_Registry::get('config')->moxie->settings->url.'/texts/about">'.$st_lang['about'].'</a></td>
                ';
        }
        $s_webMenu .= '
        </table>
        ';
	echo $s_webMenu;
?>
