<header>
<table width=100%>
<tr>
<td valign="top" class="moxietitle <?php if(empty($_SESSION['user_id'])) echo 'moxietitle_mobile_not_logged'; ?>" onclick="window.location='<?php echo Zend_Registry::get('config')->moxie->settings->url; ?>'"></td>
<td align="right" class="moxie_login_header">
<?php
global $st_lang;

$url = $_SERVER['REQUEST_URI'];
$st_url = explode("/", $url);
$st_urls = array(
    'incomes' => '/incomes',
    'expenses' => '/expenses',
    'stats' => '/stats',
    'finance' => '/finance',
    'users' => '/users'
);
$settingsUrl = Zend_Registry::get('config')->moxie->settings->url;

if(!empty($_SESSION['user_id'])) {
    ?>
    <input type="checkbox" class="checkbox" id="menu-toogle"/>
    <label for="menu-toogle" class="menu-toogle"></label>
    <nav class="nav">
        <ul>
        <?php
        echo '<li class="nav__item">'.$_SESSION['user_name'].'</li>';
        foreach($st_urls as $key => $value) {
            echo '<li class="nav__item"><a href="'.$settingsUrl.$st_urls[$key].'">'.$st_lang[$key].'</a></li>';
        }
        ?>
        <li class="nav__item"><a href="<?php echo Zend_Registry::get('config')->moxie->settings->url; ?>/login/logout"><?php echo $st_lang['logout']; ?></a></li>
        </ul>
    </nav>
    <?php
}
?>
</td>
</tr>
</table>
</header>
<!-- web menu -->
<?php
        $st_lang['users'] = $st_lang['users_title'];
        $style = 'style="display: inline-block; padding: 5px; border-radius: 5px; background-color: #D0E8F4; color: white; border 5px solid white;"';

        $s_webMenu = '
        <table cellspacing=10 class="moxie_menu">
        ';
        if (isset($_SESSION['user_id'])) {
                $s_webMenu .= '
                <td>'.$_SESSION['user_name'].'</td>';

                foreach($st_urls as $key => $value) {
                        $s_webMenu .= '<td'.(($st_url[1] == $key) ? ' '.$style : '').'><a href="'.Zend_Registry::get('config')->moxie->settings->url.$st_urls[$key].'">'.$st_lang[$key].'</a></td>';
                }
                $s_webMenu .= '<td><a href="'.Zend_Registry::get('config')->moxie->settings->url.'/login/logout">'.$st_lang['logout'].'</a></td>
                ';
        }
        else {
                $s_webMenu .= '
                <td><a href="'.Zend_Registry::get('config')->moxie->settings->url.'/">'.$st_lang['index'].'</a></td>
                <td><a href="/finance/index">'.$st_lang['finance'].'</a></td>
                <td><a href="'.Zend_Registry::get('config')->moxie->settings->url.'/texts/about">'.$st_lang['about'].'</a></td>
                ';
        }
        $s_webMenu .= '
        </table>
        ';
	echo $s_webMenu;
?>
