<div id="tags_table" class="accordion-body collapse">
	<h2 id="tags_title">
	    <?php global $st_lang; echo $st_lang['tags_title']." ".$st_lang['press_here_display']; ?>
	</h2>
    <form action="/tags/multi_update" method="POST">
        <?php
        global $st_lang;
        echo $st_lang['tags_notice'];
        ?>
        <input id="tags" name="tags" type="text" data-role="tagsinput">
        <input type="submit" value="<?php echo $st_lang['tags_update']; ?>" class="form-control">
    </form>
</div>
<br><br>

<script type="text/javascript">
    var tagList = [<?php if(!empty($this->tag_list)) echo "'".implode($this->tag_list, "','")."'"; ?>];
    $('#tags').val(tagList);
</script>