<head>
<style>
/*** taggle fixes ***/
.taggle_list {
    background: #fafafa;
    border: #ddd 1px solid;
    max-width: 90%;
}
</style>
</head>
<h2 id="tags_title"><?php global $st_lang; echo $st_lang['tags_title']." ".$st_lang['press_here_display']; ?></h2>
<div id="tags_table" style="/*display: none;*/">
    <form action="/tags/multi_update">
        Al pulsar Update se eliminarán los tags borrados.
        <div id="tags" class="tags" style="width: 100%"></div>
        <input type="submit" value="Update">
    </form>
</div>
<br><br>

<script type="text/javascript">
    var tagList = [<?php if(!empty($this->tag_list)) echo "'".implode($this->tag_list, "','")."'"; ?>];

    var taggle = new Taggle('tags', {
        tags: tagList,
        duplicateTagClass: 'bounce'
    });

    $('.taggle_list').css('width: 90%; max-width: 100%;');
</script>