<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Budgets</title>
<link rel="stylesheet" type="text/css" href="../../../moxie.css"/>
<link rel="stylesheet" type="text/css" href="../../../dropdown.css"/>
<script type="text/javascript" src="../../../helpers.js"></script>
<script type="text/javascript" src="../../../calendar.js"></script>
<script type="text/javascript" src="../../../form.js"></script>
<script type="text/javascript">
function getSum() {
	var node_list = document.getElementsByTagName('input');
	var sum = 0;
	for (var i = 0; i < node_list.length; i++) {
	    var node = node_list[i];
	 
	    if (node.getAttribute('type') == 'text') {
	        sum = sum + Math.round(node.value);
	    }
	}
	document.getElementById('sum').innerHTML = '<B>' + sum + ' &euro;</B>';
}
</script>
</head>

<body>
<h2>Budget</h2>
<table width=50%>
<?php
$f_initialBudget = 0;
foreach ($this->categories as $key => $value) {
	echo '
	<tr>
	<form id="login" enctype="application/x-www-form-urlencoded" action="/budgets/add" method="post" class="budget">
	<td>
	'.$value['name1'].' '.$value['name2'].'
	</td>
	<td align="right">
	<input type="hidden" name="category" id="category" value="'.$value['id1'].'">
	<input type="text" name="amount" onChange="getSum()" value="'.$value['budget'].'" style="text-align: right;">
	</td>
	<td>
	<input type="submit" value="Send">
	</td>
	</form>
	</tr>
	';
	$f_initialBudget += $value['budget'];
}
?>
<tr><td></td><td align="right"><span id="sum"><B><?= $f_initialBudget?> &euro;</B></span></td><td></td></td></tr>
</table>
</body>
</html>