<head>
    <script src="/bower_components/clipboard/dist/clipboard.js"></script>
    <script src="/js/sheets/data.js?v=1"></script>
</head>

<div class="moxie-container">
<?php
global $st_lang;
echo $this->partial('sheets/select_sheet.phtml', array('sheet_list'=>$this->sheet_list, 'sheet_list_form' => $this->sheet_list_form));
?>
<div class="moxie_expenses_form_div" id="sheet_create_button">
<input type="submit" onclick="$('#sheet_create').toggle(); $('#sheet_create_button').toggle();" value="<?php echo $st_lang['sheets_create_new']; ?>" class="btn btn-info">
</div>

<?php
echo $this->partial('sheets/create.phtml');
?>

</div>
