<head>
<script type="text/javascript" language="text/javascript">
function redirect() {
	var unique_id = $('#sheet_id').find(":selected").val();
	window.location.replace("/sheets/view/id/" + unique_id);
}
</script>
</head>

<div class="moxie-container">
<div>
<?php
// for data in sheet_list
if (empty($this->sheet_list)) {
	?>
	No tienes sheets.
	<?php
}
else {
	echo "My sheets
<select id='sheet_id' name='sheet_id' onchange='redirect()'>
<option>-</option>
";
	echo "Selecciona una sheets.";
	foreach ($this->sheet_list as $s) {
		echo "<option value='".$s['unique_id']."'>".$s->name."</option>";
	}
}
?>
</select>
</div>
<div>
</b><a href="/sheets/create">Crear nueva sheets</a>
</div>
</div>
