<script src="/bower_components/clipboard/dist/clipboard.min.js"></script>
<script src="/js/sheets/data.js"></script>
<div class="moxie-container">
<div>
<div id="messages">
<?php
global $st_lang;
if(!empty($this->messages)) {
	foreach($this->messages as $e) {
		echo "<div>".$e."</div>";
	}
}
?>
</div>
<div id="errors">
<?php
if(!empty($this->errors)) {
	foreach($this->errors as $e) {
		echo "<div>".$e."</div>";
	}
}
?>
</div>
<div class="sheets_select_sheet">
<?php
echo $this->partial('sheets/select_sheet.phtml', array('sheet_list'=>$this->sheet_list, 'sheet_list_form' => $this->sheet_list_form));
?>
</div>
<?php
if (isset($this->sheet)) {
?>
	<div class="moxie_expenses_form_div" style="padding: 10px">
	<h1>
		<a href="/sheets/view/id/<?php echo $this->sheet['unique_id']; ?>"><?php echo $this->sheet['name']; ?></a>
		<span>
		<img class="btn"
		style="width: 24px; height: 24px; background: #ffffff; border: 0px; padding: 0px; margin: 0px;" src="/img/copy.png"
		alt="<?php echo $st_lang['sheets_copy_to_clipboard']; ?>"
		title="<?php echo $st_lang['sheets_copy_to_clipboard']; ?>">
		</span>
		
		
	</h1>
	</div>
	
	<?php
	if (empty($this->sheet['closed_at'])) {
	?>
	<div id="forms">
		<div class="moxie_expenses_form_div moxie_expenses_form_left">
			<div id="add_user_container" style="padding: 10px">
	 			<span id="add_user_button">
				<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
					<i class="material-icons" style="background-color: #0b77b7">+</i>
				</button>
				<span style="font-size: 18px; font-weight: bold;">Añadir usuario:</span>
				</span>
				<span id="add_user_form" style="display: none">
					<form action="/sheets/add_user" method="POST">
					<p>
					Introduce la dirección de correo de la persona con la que compartes gastos.&nbsp;
					Si introduces un nombre de usuario existente, asociaremos esta hoja a su cuenta.<br>
					</p>
					Nombre <input type="text" id="user" name="user"><br>
					<input type="hidden" name="id_sheet" value="<?php echo $this->sheet['unique_id']; ?>">
					<input type="submit" value="Agregar">
					</form>
				</span>
			</div>
			
			<div style="max-width: 500px; padding: 10px;">
			<span id="add_user_button">
				<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
					<i class="material-icons" style="background-color: #0b77b7">+</i>
				</button>
				<span style="font-size: 18px; font-weight: bold;">Añadir gasto:</span>
			</span>
			
			
			<form action="/sheets/add" method="POST">
			Usuario
			<select id="id_sheet_user" name="id_sheet_user">
			<?php
			foreach($this->sheet['users'] as $user) {
				$displayName = (isset($user['login']) ? $user['login'] : $user['email']);
				echo '<option value="'.$user['id_sheet_user'].'">'.$displayName.'</option>';
			}
			?>
			</select><br>
			<label for="amount">Importe</label>
			<input type="text" id="amount" name="amount" placeholder='0.00'>
			<label for="note">Nota</label>
			<input type="text" id="note" name="note">
			<label for="date">Fecha</label>
			<input type="date" id="date" name="date" value="<?php echo date('Y-m-d'); ?>">
			<input type="hidden" name="id_sheet" value="<?php echo $this->sheet['unique_id']; ?>">
			<input type="submit" value="Agregar">
			</form>
			<?php //echo $this->sheet_form; ?>
			</div>
		
			<div>
			<form action="/sheets/close/id/<?php echo $this->sheet['unique_id']; ?>" method="POST">
			<input type="hidden" name="id_sheet" value="<?php echo $this->sheet['unique_id']; ?>">
			<input type="submit" value="Cerrar hoja">
			</form>
			<?php
			}
			else {
			?>
			<form action="/sheets/copy/id/<?php echo $this->sheet['unique_id']; ?>" method="POST">
			<input type="hidden" name="id_sheet" value="<?php echo $this->sheet['unique_id']; ?>">
			<button onclick="submit()">Copiar a mis gastos</button> usando la categoría&nbsp;
			<select name="id_category" id="id_category">
			<?php
			foreach($this->categories as $k => $c) {
				echo "<option value='".$k."'>".$c."</option>";
			}
			?>
			</select>
			</form>
			<?php
			}
			?>
			</div>
		
		</div>
	
		<div id="search_box" class="moxie_expenses_form_div moxie_expenses_form_right">
			Reparto
		</div>
	</div>
	
	<table class="list moxie moxie-data" style="width: 100%">
	<tr>
	<th style="width: 5%"></th>
	<th style="20%">Fecha</th>
	<th align="left">Nota</th>
	<?php
	foreach($this->sheet['users'] as $k => $user) {
		$name = empty($user['login']) ? $user['email'] : $user['login'];
		echo "<th align='right'>".$name."</th>";
		$this->sheet['users'][$k]['total'] = 0;  // add column total for user
	}
	?>
	</tr>
	<?php
	$total = 0;
	foreach($this->sheet['expenses'] as $e) {
		$total += $e['amount'];
		// distinct_users_list will mark column for each row
		echo "<tr><td>&nbsp;</td>";
		echo "<td align='center'>".explode(" ", $e['date'])[0]."</td>";
		echo "<td align='left'>".$e['note']."</td>";
		foreach($this->sheet['users'] as $k => $du) {
			if ($e['id_sheet_user'] == $du['id_sheet_user']) {
				echo "<td align='right'>".$e['amount']." &euro;</td>";
				$this->sheet['users'][$k]['total'] += $e['amount'];
			}
			else {
				echo "<td align='right'>0.00 &euro;</td>";
			}
		}
		echo "</tr>";
	}
	$average = ($this->sheet['distinct_users'] > 0) ? $total / $this->sheet['distinct_users'] : 0;
	?>
	
	<tr>
	<th></th>
	<th></th>
	<th><?php echo number_format($total, 2); ?> &euro;</th>
	<?php
	foreach($this->sheet['users'] as $user) {
		echo "<th align='right'>".number_format($user['total'], 2)." &euro;</th>";
	}
	?>
	</tr>
	<tr>
	<th></th>
	<th></th>
	<th></th>
	<?php
	foreach($this->sheet['users'] as $user) {
		$current = -($average - $user['total']);
		if($current <= 0) {
			// debes pasta
			$color = '#ff0000';
		}
		else {
			// has pagado de mas
			$color = '#00ff00';
		}
		echo "<th align='right' style='color: ".$color."'>".number_format($current, 2)." &euro;</th>";
	}
	?>	
	</tr>
	
	</table>
<?php
}
?>
</div>
</div>
