<div class="moxie-container">
<div>
<div id="errors">
<?php
if(!empty($this->errors)) {
	foreach($this->errors as $e) {
		echo "<div>".$e."</div>";
	}
}
?>
</div>
<?php
if (isset($this->sheet)) {
?>
	Identificador único de esta página de gastos compartidos:&nbsp;
	<a href="/sheets/view/id/<?php echo $this->sheet['unique_id']; ?>"><?php echo $this->sheet['name']; ?></a><br>
	<div>
	Añadir usuario:
	<form action="/sheets/add_user" method="POST">
	<p>
	Introduce la dirección de correo de la persona con la que compartes gastos.&nbsp;
	Si introduces un nombre de usuario existente, asociaremos esta hoja a su cuenta.<br>
	</p>
	Nombre <input type="text" id="user" name="user"><br>
	<input type="hidden" name="id_sheet" value="<?php echo $this->sheet['unique_id']; ?>">
	<input type="submit" value="Agregar">
	</form>
	</div>
	
	<div>
	Añadir gasto:
	<form action="/sheets/add" method="POST">
	Usuario
	<select id="id_sheet_user" name="id_sheet_user">
	<?php
	foreach($this->sheet['users'] as $user) {
		error_log(print_r($user,true));
		$displayName = (isset($user['login']) ? $user['login'] : $user['email']);
		echo '<option value="'.$user['id_user_sheet'].'">'.$displayName.'</option>';
	}
	?>
	</select><br>
	<label for="note">Nota</label>
	<input type="text" id="note" name="note">
	<label for="amount">Gasto</label>
	<input type="text" id="amount" name="amount">
	<label for="date">Fecha</label>
	<input type="date" id="date" name="date" value="<?php echo date('Y-m-d'); ?>">
	<input type="hidden" name="id_sheet" value="<?php echo $this->sheet['unique_id']; ?>">
	<input type="submit" value="Agregar">
	</form>
	</div>
	
	<div>
	<form action="/sheets/close/id/<?php echo $this->sheet['unique_id']; ?>" method="GET">
	<input type="submit" value="Cerrar hoja">
	</form>
	</div>
	
	<table class="list moxie moxie-data" style="width: 100%">
	<tr>
	<th></th>
	<th>Fecha</th>
	<th align="left">Nota</th>
	<?php
	foreach($this->sheet['users'] as $k => $user) {
		$name = empty($user['login']) ? $user['email'] : $user['login'];
		error_log("name : ".$name);
		echo "<th align='right'>".$name."</th>";
		$this->sheet['users'][$k]['total'] = 0;  // add column total for user
	}
	?>
	</tr>
	<?php
	$total = 0;
	foreach($this->sheet['expenses'] as $e) {
		$total += $e['amount'];
		// distinct_users_list will mark column for each row
		echo "<tr><td>&nbsp;</td>";
		echo "<td align='center'>".explode(" ", $e['date'])[0]."</td>";
		echo "<td align='left'>".$e['note']."</td>";
		foreach($this->sheet['distinct_users_list'] as $k => $du) {
			if ($e['id_sheet_user'] == $du) {
				echo "<td align='right'>".$e['amount']." &euro;</td>";
				$this->sheet['users'][$k]['total'] += $e['amount'];
			}
			else {
				echo "<td></td>";
			}
		}
		echo "</tr>";
	}
	$average = $total / $this->sheet['distinct_users'];
	?>
	
	<tr>
	<th></th>
	<th></th>
	<th><?php echo number_format($total, 2); ?> &euro;</th>
	<?php
	foreach($this->sheet['users'] as $user) {
		echo "<th align='right'>".number_format($user['total'], 2)." &euro;</th>";
	}
	?>
	</tr>
	<tr>
	<th></th>
	<th></th>
	<th></th>
	<?php
	foreach($this->sheet['users'] as $user) {
		$current = $average - $user['total'];
		if($current > 0) {
			// debes pasta
			$color = '#ff0000';
		}
		else {
			// has pagado de mas
			$color = '#00ff00';
		}
		echo "<th align='right' style='color: ".$color."'>".number_format($current, 2)." &euro;</th>";
	}
	?>	
	</tr>
	
	</table>
	
<?php
} else if (isset($this->errors)) {
	foreach($this->errors as $e) {
?>
<span><?php echo $e; ?></span>
<?php
	}
} else {
?>
<form action="/sheets/create" method="POST">

<label for="name">Nombre</label>
<input type="text" id="name" name="name">

<input type="submit" value="Crear">

</form>
<?php
}
?>
</div>
</div>
