<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php global $st_lang; echo $st_lang['stats']; ?></title>
<link rel="stylesheet" type="text/css" href="../../../moxie.css"/>
</head>

<body>
<h2><?= $st_lang['register']; ?></h2>
<?php
$this->form->setAction('/login/registeruser')->setMethod('post');
echo $this->form;
?>
</body>
</html>