<?php
global $st_lang;
echo "<h2>".$st_lang['register']."</h2>";
?>
<br>
<p style="color: #ff0000; padding: 10px; border: 10px;"><?php echo $this->message; ?></p>
<?php
include("application/3rdparty/simple-php-captcha/simple-php-captcha.php");
$_SESSION['captcha'] = simple_php_captcha();
$this->form->setAction('/login/registeruser')->setMethod('post');
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>">
<dl class="zend_form">
<?php
foreach ($this->form->getElements() as $element) {
	if($element->getLabel() != "Send") {
		echo '<dt id="'.$element->getId().'"><label for="'.$element->getId().'" class="optional">'.$element->getLabel().'</label></dt>';
		if($element->getType()=="Zend_Form_Element_Password")
			echo '<dd><input type="password" name="'.$element->getId().'" id="'.$element->getId().'"></dd>';
		else
			echo '<dd><input type="text" name="'.$element->getId().'" id="'.$element->getId().'"></dd>';
	}
}
echo '<dt id="captcha"><label>Captcha</label></dt>'
	.'<dd><input type="text" name="captcha" id="captcha"></dd>';
echo '<img src="'.$_SESSION['captcha']['image_src'].'">';
?>
<dt id="submit-label">&#160;</dt><dd id="submit-element">
<input type="submit" name="submit" id="submit" value="Send"></dd>
</dl></form>
<br>
