<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php global $st_lang; echo $st_lang['stats']; ?></title>
<link rel="stylesheet" type="text/css" href="../../../moxie.css"/>
</head>

<body>
<?php
include '/html/web.php';
echo web_header(Zend_Registry::get('config')->moxie->app->name, Zend_Registry::get('config')->moxie->settings->url);
echo web_menu();
?>

<h2><?= $st_lang['register']; ?></h2>
<?php
echo $this->text;
include($_SERVER['DOCUMENT_ROOT']."/application/3rdparty/simple-php-captcha/simple-php-captcha.php");
$_SESSION['captcha'] = simple_php_captcha();
$this->form->setAction('/login/registeruser')->setMethod('post');
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>">
<dl class="zend_form">
<?php
foreach ($this->form->getElements() as $element) {
	if($element->getLabel() != "Send") {
		echo '<dt id="'.$element->getId().'"><label for="'.$element->getId().'" class="optional">'.$element->getLabel().'</label></dt>';
		if($element->getType()=="Zend_Form_Element_Password")
			echo '<dd><input type="password" name="'.$element->getId().'" id="'.$element->getId().'"></dd>';
		else
			echo '<dd><input type="text" name="'.$element->getId().'" id="'.$element->getId().'"></dd>';
	}
}
echo '<dt id="captcha"><label>Captcha</label></dt>'
	.'<dd><input type="text" name="captcha" id="captcha"></dd>';
echo '<img src="'.$_SESSION['captcha']['image_src'].'">';
?>
<dt id="submit-label">&#160;</dt><dd id="submit-element">
<input type="submit" name="submit" id="submit" value="Send"></dd>
</dl></form>
<br>
</body>
</html>
