<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Budgets</title>
<link rel="stylesheet" type="text/css" href="../../../moxie.css"/>
</head>

<body>
<h2>Registration successfully!</h2>
Now you can log in with your login and password to start using Moxie.
</body>
</html>