<script type="text/javascript" language="text/javascript">
	var dodeleteUrl = "<?php echo Zend_Registry::get('config')->moxie->settings->url; ?>/expenses/dodelete/id/";
	var getyearUrl = "<?php echo Zend_Registry::get('config')->moxie->settings->url; ?>/expenses/year";
	var settingsMonth = <?php echo (isset($this->month) ? $this->month : date('n')); ?>;
	var settingsYear = <?php echo $this->year; ?>;
	var getmonthUrl = "<?php echo Zend_Registry::get('config')->moxie->settings->url; ?>/expenses/month/month/"+settingsMonth+"/year/"+settingsYear;
	console.log(getmonthUrl);
</script>
<script type="text/javascript" src="/js/expenses/data.js"></script>
<table width=100%>
<?php global $st_lang; ?>
<td><a href="/expenses/index/month/<?php if ($this->month == 1) echo 12; else echo $this->month-1;?>/year/<?php if ($this->month == 1) echo $this->year-1; else echo $this->year;?>"><div class="moxieicon moxieprevious"></div> <?php echo $st_lang['expenses_last_month']; ?></a></td>
<td><span class="moxie_header_date"><?php echo date("M Y", strtotime("01-".$this->month."-".$this->year)); ?></span></td>
<td><a href="/expenses/index/month/<?php if ($this->month == 12) echo 1; else echo $this->month+1;?>/year/<?php if ($this->month == 12) echo $this->year+1; else echo $this->year;?>"><div class="moxieicon moxienext"></div> <?php echo $st_lang['expenses_next_month']; ?></a></td>
</table>
<?php
$i_expensePK = $this->form->getValue('id');
$checked = ($this->form->getElement('in_sum') == 1) ? "checked": "";
if (isset($i_expensePK)) {
?>
	<form id="login" enctype="application/x-www-form-urlencoded" action="/expenses/update" method="post" class="moxie_form">
	<div>Check/uncheck to show in totals <input type="checkbox" class="my-checkbox" id="<?php echo $i_expensePK; ?>" name="<?php echo $i_expensePK; ?>" onClick="markLine(<?php echo $i_expensePK; ?>);" <?php echo $checked; ?>"/></div>
<?php
	echo $this->form->getElement('user_owner');
	echo $this->form->getElement('id');
	$amount = $this->form->getValue('amount');
}
else {
?>
	<form id="login" enctype="application/x-www-form-urlencoded" action="/expenses/add" method="post" class="moxie_form">
<?php
	$amount = '';
}
?>
<dt id="amount-label"><label for="amount" class="optional"><?php echo $st_lang['expenses_amount']; ?></label></dt>
<dd>
<input type="number" id="amount" name="amount" step="any" placeholder="0,00" value="<?php echo $amount; ?>">
</dd>

<?php
echo $this->form->getElement('note');
echo '<div class="date">'.$this->form->getValue('date').'</div>';
?>
<script>
$(document).ready(function() {
    enableSelectBoxes();
});

	function enableSelectBoxes(){
		$('div.selectBox').each(function(){
			$(this).children('span.selected').html($(this).children('div.selectOptions').children('span.selectOption:first').html());
			$(this).attr('value',$(this).children('div.selectOptions').children('span.selectOption:first').attr('value'));
					
			$(this).children('span.selected,span.selectArrow').click(function(){
				if($(this).parent().children('div.selectOptions').css('display') == 'none'){
					$(this).parent().children('div.selectOptions').css('display','block');
				}
				else
				{
					$(this).parent().children('div.selectOptions').css('display','none');
				}
			});
					
			$(this).find('span.selectOption').click(function(){
				$(this).parent().css('display','none');
				$(this).closest('div.selectBox').attr('value',$(this).attr('value'));
				$(this).parent().siblings('span.selected').html($(this).html());
				$('#category').val($(this).attr('value'));
			});
		});
	} 
</script>
<dt id="category-label"><label for="category" class="optional">Categoría</label></dt
<dd id="category-element">
<div class='selectBox'>
    <span class='selected'></span>
    <span class='selectArrow'>&#9660</span>
    <div class="selectOptions" >
<?php
foreach($this->form->getElement('category') as $key => $option) {
	if($key == "options") {
		foreach($option as $key2 => $option2) {
			echo "<span class='selectOption' value='".$key2."'>".$option2."</span>";
		}
	}
}
?>
    </div>
</div>
<input type="hidden" name="category" id="category" value=""/>
</dd>
<?php
/*echo $this->form->getElement('note');
echo '<div class="date">'.$this->form->getValue('date').'</div>';*/
echo $this->form->getElement('submit');
if(isset($i_expensePK)) {
	echo '<input type="button" value="'.$st_lang['expenses_delete'].'" onclick=\'confirmDelete("' . $i_expensePK . $s_dateGet . '")\'/>';
}
echo '</form>';
?>
<table class="list moxie moxie-data" id="mytable">
<tr>
<td colspan=4 align=right>
Filtrar por <select id="category_filter" onchange="filter();">
<option value="0">---</option>
<?php
foreach ($this->form->getElement('category') as $key => $value) {
	if ($key == "options") {
		foreach ($value as $key2 => $value2) {
			echo '<option value="'.$key2.'">'.$value2.'</option>';
		}
	}
}
?>
</select>
</td>
</tr>
<?php
$i = 0;
$f_totalAmount = 0;
$f_currentAmount = 0;
$b_showTotalAmount = false;
foreach ($this->list as $key=>$value) {
	$i++;
	$bgcolor = ($i % 2 == 0) ? "background: #FFFFFF" : "background: #D0E8F4";

	$checked = ($value['in_sum'] == '1') ? "checked":"";
	$s_dateGet = (isset($this->month) && isset($this->year)) ? '/year/'.$this->year.'/month/'.$this->month : '';
	$expense_date = date('d-m-Y', strtotime($value['date']));
	
	echo '
<tr id="tr'.$value['id'].'">
<td class="list moxie_edit" style="'.$bgcolor.'"><a class="moxieedit" href="/expenses/edit/id/'.$value['id'].$s_dateGet.'"><div class="moxieicon moxieedit"></div></a></td>
<td class="list moxie_category" style="'.$bgcolor.';"><div alt="'.$value['description'].'" title="'.$value['description'].'">'.$value['name'].'</div></td>
<!--<td align="center" class="list moxie_date" style="'.$bgcolor.'">'.$expense_date.'</td>-->
<td class="list moxie_note" style="'.$bgcolor.';"><span alt="'.$expense_date.'" title="'.$expense_date.'">'.$value['note'].'</span></td>
<td align="right" class="list moxie_amount" style="'.$bgcolor.';"><span id="val'.$value['id'].'">'.number_format($value['amount'],2).' &euro;</span></td>
</tr>';

	$f_totalAmount = $f_totalAmount + $value['amount'];
	$f_currentAmount += ($value['in_sum'] == 1) ? $value['amount'] : 0;
	$b_showTotalAmount = ($value['in_sum'] != 1) || $b_showTotalAmount;
}

$s_total = number_format($f_currentAmount,2)." &euro;";
if($b_showTotalAmount) {
	$s_total .= '<br><span class="total_amount">'.number_format($f_totalAmount, 2)." &euro;";
}

?>
<tr>
<td colspan=4 align="right" class="list list_money"><span id="total"><?php echo $s_total; ?></span></td>
</tr>
</table>
<br><br><br>
