<?php
global $st_lang;
?>
<script type="text/javascript" language="text/javascript">
	var deleteUrl = "<?php echo Zend_Registry::get('config')->moxie->settings->url; ?>/expenses/delete/id/";
    var deleteMessage = "<?php echo $st_lang['expenses_delete_message']; ?>";
	var tagList = [<?php if(!empty($this->tags)) echo "'".implode($this->tags, "','")."'"; ?>];
    var usedTagList = [<?php if(!empty($this->used_tag_list)) echo "'".implode($this->used_tag_list, "','")."'"; ?>];
	var tagsPlaceholder = "<?php echo $st_lang['tags_placeholder']; ?>";
</script>
<script type="text/javascript" src="/js/expenses/data.js?v=4"></script>

<div id="form">
<div class="form-group moxie_expenses_form_div moxie_expenses_form_left">
<?php
$i_expensePK = $this->form->getValue('id');
$checked = ($this->form->getValue('in_sum') == "1") ? "checked": "";
?>
	<?php if(isset($this->favourites_json) && $this->favourites_json != "[]") { ?>
	<div id="favourites_container">
		<button data-toggle="collapse" data-target="#favourites_list" class="btn btn-info">Favoritos</button>
		<span id="favourites_list" class="collapse">
			<script type="text/javascript">
				favourite_data = <?php echo $this->favourites_json; ?>;
			</script>
			<form class="form-group">
				<select id="favourites" name="favourites" class="form-control">
					<option value=""></option>
				</select>
			</form>
		</span>
	</div>
	<?php } 
	
	echo $this->form;
?>
</div>
<div id="search_box" class="moxie_expenses_form_div moxie_expenses_form_right">
<?php
echo $this->partial('common/filter.phtml', array('search_form' => $this->search_form));
?>
</div>
</div>