<?php
global $st_lang;
?>
<script type="text/javascript" language="text/javascript">
	var deleteUrl = "<?php echo Zend_Registry::get('config')->moxie->settings->url; ?>/expenses/delete/id/";
    var deleteMessage = "<?php echo $st_lang['expenses_delete_message']; ?>";
	var tagList = [<?php if(!empty($this->tags)) echo "'".implode($this->tags, "','")."'"; ?>];
    var usedTagList = [<?php if(!empty($this->used_tag_list)) echo "'".implode($this->used_tag_list, "','")."'"; ?>];
	var tagsPlaceholder = "<?php echo $st_lang['tags_placeholder']; ?>";
</script>
<script type="text/javascript" src="/js/expenses/data.js"></script>
<table width=100%>
<td align="left"><a href="/expenses/index/month/<?php if ($this->month == 1) echo 12; else echo $this->month-1;?>/year/<?php if ($this->month == 1) echo $this->year-1; else echo $this->year;?>"><div class="moxieicon moxieprevious"></div><span class="moxieprevious"> <?php echo $st_lang['expenses_last_month']; ?></span></a></td>
<td align="center"><span class="moxie_header_date"><?php echo date("M Y", strtotime("01-".$this->month."-".$this->year)); ?></span></td>
<td align="right"><a href="/expenses/index/month/<?php if ($this->month == 12) echo 1; else echo $this->month+1;?>/year/<?php if ($this->month == 12) echo $this->year+1; else echo $this->year;?>"><div class="moxieicon moxienext"></div><span class="moxienext"> <?php echo $st_lang['expenses_next_month']; ?></span></a></td>
</table>
<br>

<div id="form">
<div class="moxie_expenses_form_div moxie_expenses_form_left">
<?php
echo '<h2>'.$st_lang['expenses_header'].'</h2>';
$i_expensePK = $this->form->getValue('id');
$checked = ($this->form->getValue('in_sum') == "1") ? "checked": "";
if (isset($i_expensePK)) {
?>
	<form id="login" enctype="application/x-www-form-urlencoded" action="/expenses/update" method="post" class="moxie_form">
	<input type="hidden" class="my-checkbox" id="<?php echo $i_expensePK; ?>" name="<?php echo $i_expensePK; ?>"/>
	<div><?php echo $st_lang['in_sum_message']; ?><input type="checkbox" class="my-checkbox" id="in_sum" name="in_sum" onClick="markLine(<?php echo $i_expensePK; ?>);" <?php echo $checked; ?>/></div>
<?php
	echo $this->form->getElement('user_owner');
	echo $this->form->getElement('id');
}
else {
?>
	<form id="login" enctype="application/x-www-form-urlencoded" action="/expenses/add" method="post" class="moxie_form">
<?php
}
echo $this->form->getElement('amount');
echo $this->form->getElement('note');
?>
<dt id="date-label"><label for="date" class="optional"><?php echo $st_lang['expenses_date']; ?></label></dt>
<dd><input type="date" id="date" name="date" value="<?php echo $this->form->getValue('date'); ?>"></dd>
<?php
echo $this->form->getElement('category');
?>
<dt for="form_tags">Tags</dt>
<dd id="form_tags" class="dd_taggle_list">
	<div id="tags" class="div_taggle_list"></div>
</dd>
<?php
echo $this->form->getElement('submit');
if(isset($i_expensePK)) {
	echo '<input type="button" class="moxiedelete" value="'.$st_lang['expenses_delete'].'" onclick=\'confirmDelete("' . $i_expensePK . '")\'/>';
}
?>
</form>
</div>
<div id="search_box" class="moxie_expenses_form_div moxie_expenses_form_right">
<?php
echo $this->partial('common/filter.phtml', array('search_form' => $this->search_form));
?>
</div>
</div>
