<a href="/expenses/index/month/<?php if ($this->month == 1) echo 12; else echo $this->month-1;?>/year/<?php if ($this->month == 1) echo $this->year-1; else echo $this->year;?>">Last</a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="/expenses/index/month/<?php if ($this->month == 12) echo 1; else echo $this->month+1;?>/year/<?php if ($this->month == 12) echo $this->year+1; else echo $this->year;?>">Next</a>
<?php
$i_expensePK = $this->form->getElement('id');
if (isset($i_expensePK)) {
	echo '<form id="login" enctype="application/x-www-form-urlencoded" action="/expenses/update" method="post">';
	echo $this->form->getElement('user_owner');
	echo $this->form->getElement('id');
}
else {
	echo '<form id="login" enctype="application/x-www-form-urlencoded" action="/expenses/add" method="post">';
}
echo $this->form->getElement('amount');
echo $this->form->getElement('category');
echo "\n";
echo $this->form->getElement('note');
if (isset($i_expensePK)) {
	echo $this->form->getElement('date');	
}
else {
	echo '<div class="date"></div>';
}
echo $this->form->getElement('submit');
echo '</form>';
?>
<pre>
<?php
$f_totalAmount = 0;
echo '
<table border=1 width=600 class="list">
<td colspan=6>
Marcar:&nbsp;
<span onClick="markAll(0);" alt="Desmarcar todos" title="Desmarcar todos">Ninguno</span>&nbsp;
<span onClick="markAll(1);" alt="Marcar todos" title="Marcar todos">Todos</span>
</td>
';

foreach ($this->list as $key=>$value) {
	$checked = ($value['in_sum'] == '1') ? "checked":"";
	$s_dateGet = (isset($this->month) && isset($this->year)) ? '/year/'.$this->year.'/month/'.$this->month : '';
	$st_expenseDate = explode(' ',$value['expense_date']);
	$expense_date = '<span alt="'.$st_expenseDate[1].'" title="'.$st_expenseDate[1].'">'.$st_expenseDate[0].'</span>';
	
	echo '
<tr>
<td class="list" width="10"><input type="checkbox" class="my-checkbox" id="'.$value['id'].'" name="'.$value['id'].'" onClick="markLine('.$value['id'].');" '.$checked.'></td>
<td class="list" width="30"><span class="linked" onclick=\'confirmDelete("'.$value['id'].$s_dateGet.'")\'>X</span>&nbsp;<a href="/expenses/edit/id/'.$value['id'].$s_dateGet.'">E</a></td>'
.'<td align="right" class="list">'.number_format($value['amount'],2).' &euro;</td>
<td width="100" align="center" class="list">'.$expense_date.'</td>
<td class="list" width="80"><div alt="'.$value['description'].'" title="'.$value['description'].'">'.$value['name'].'</div></td>
<td class="list">'.$value['note'].'</td>
</tr>';
	$f_totalAmount = $f_totalAmount + $value['amount'];
}
echo '<tr>
<td colspan=2></td>
<td>'.number_format($f_totalAmount,2).' &euro;</td><td colspan=3></td></tr>
</table>
';
?>
</pre>
