<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Expenses</title>
<script type="text/javascript" language="text/javascript">
	var year = <?php echo $this->year; ?>;
	var month = <?php echo $this->month; ?>;
	function markAll(option) {
		window.location="/expenses/markall/option/"+option+"/year/"+year+"/month/"+month;
	}

	function markLine(id) {
		window.location="/expenses/markline/id/"+id;
	}
</script>
<link rel="stylesheet" type="text/css" href="../../../moxie.css"/>
<link rel="stylesheet" type="text/css" href="../../../dropdown.css"/>
<script type="text/javascript" src="../../../helpers.js"></script>
<script type="text/javascript" src="../../../calendar.js"></script>
<script type="text/javascript" src="../../../form.js"></script> 

</head>
</head>
<body>

<h2>Expenses</h2>

<table>
<tr>
<td>
<?php
echo $this->partial('expenses/data.phtml',
					array('form'=>$this->form, 'list'=>$this->list,'year'=>$this->year,'month'=>$this->month));
?>
</td>
<td valign="top">
<?php
echo $this->partial('expenses/stats.phtml', array('year'=>$this->year,'month'=>$this->month));
?>
</td></tr></table>
</body>
</html>