<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php global $st_lang; echo $st_lang['expenses']; ?></title>
<script type="text/javascript" language="text/javascript">
	var year = <?php echo $this->year; ?>;
	var month = <?php echo $this->month; ?>;
	function markAll(option) {
		window.location="/expenses/markall/option/"+option+"/year/"+year+"/month/"+month;
	}

	function markLine(id) {
		window.location="/expenses/markline/id/"+id;
	}

	function confirmDelete(id) {
		var response;
		response = confirm("Are you sure to delete this expense?");
		if (response == true) {
			window.location="/expenses/delete/id/"+id;
		}
	}

	function filter() {
		var chosen;
		var redirect;
		chosen = document.getElementById('category_filter').selectedIndex;
		redirect = document.getElementById('category_filter').options[chosen].value;
		window.location="/expenses/index/category_filter/"+redirect;
	}
</script>
<link rel="stylesheet" type="text/css" href="/moxie.css"/>
<link rel="stylesheet" type="text/css" href="/dropdown.css"/>
<script type="text/javascript" src="/js/helpers.js"></script>
<script type="text/javascript" src="/js/calendar.js"></script>
<script type="text/javascript" src="/js/form.js"></script>
<script type="text/javascript" src="/js/jquery.js"></script>

</head>
<body>

<h2><?php echo $st_lang['expenses']; ?></h2>

<table>
<tr>
<td valign="top">
<?php
echo $this->partial('expenses/data.phtml',
					array('form'=>$this->form, 'list'=>$this->list,'year'=>$this->year,'month'=>$this->month));
?>
</td>
<td valign="top">
<?php
echo $this->partial('expenses/stats.phtml',
					array('budget'=>$this->budget,'expenses'=>$this->expenses,'year'=>$this->year,'month'=>$this->month));
?>
</td></tr></table>
</body>
</html>
