<!-- Graphic -->
<?php
global $st_lang;
$st_budget = $this->budget;

$s_out = '
<table class="table table-striped" id="mytable" width="100%">
<tr><td></td><td align="right">'.$st_lang['expenses_expended'].'</td>';
if (!empty($st_budget)) $s_out .= '<td align="right">'.$st_lang['expenses_budget'].'</td></tr>';

$st_jsonData = array();
$current = 0;
$total = 0;
$budget_total = 0;
foreach ($this->expenses as $key => $data) {
	$amount = $data['sum(e.amount)'];
	$current = $data['id'];
	$category_name = $data['name'];
	$total = $total + $amount;
	$st_jsonData[] = "['".$category_name."', ".$amount."]";
	$budget_amount = (isset($st_budget[$data['id']])) ? $st_budget[$data['id']] : 0;
	$budget_color = ($budget_amount <= $amount) ? '#FF0000' : '#00FF00';
	$s_out .= '<tr>'
			.'<td><a href="/expenses/index/category/'.$data['id'].'/month/'.$this->month.'/year/'.$this->year.'">'.$category_name.'</a></td>'
			.'<td align="right">'.number_format($amount,2).' &euro;</td>';
	if(!empty($st_budget)) {
		$s_out .= '<td align="right" style="color: '.$budget_color.';">'.$budget_amount.' &euro;</td>';
		$budget_total = $budget_total + $budget_amount;
	}
	$s_out .= '</tr>';
}
$s_out .= '<tr><td><B>TOTAL</B></td><td align="right"><B>'.number_format($total,2).' &euro;</B></td>';
if (!empty($st_budget)) {
	$budget_color = ($budget_total <= $total) ? '#FF0000' : '#00FF00';
	$s_out .= '<td align="right" style="color: '.$budget_color.';">'.number_format($budget_total,2).' &euro;</td>';
}
$s_out .= '</tr></table>';
$s_jsonData = "[".implode(",", $st_jsonData)."]";
?>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
	var pieData = <?php echo $s_jsonData; ?>;
	var pieTitle = "<?php echo $st_lang['expenses_monthly']; ?>";
	var barChartData = <?php echo $this->month_expenses; ?>;
	var barTitle = "<?php echo $st_lang['expenses_by_months']; ?>";
</script>
<script type="text/javascript" src="/js/expenses/stats.js"></script>
<div id="expenses_month"></div>
<br><br>
<?php
echo $s_out;
?>
<br><br>
<div id="expenses_all"></div>
<br><br>
<?php $this->getHelper('Web')->printToTop(); ?>
