<!-- Graphic -->
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="/js/expenses/stats.js?v=10.6"></script>
<div id="expenses_month"></div>

<?php
global $st_lang;

function getJsonDataString($expenses) {
    $st_jsonData = array();
    foreach($expenses as $key => $data) {
        $category_name = $data['name'];
        $amount = $data['sum(e.amount)'];
        $st_jsonData[] = "['" . $category_name . "', " . $amount . "]";
    }
    return "[".implode(",", $st_jsonData)."]";
}

$s_out = '
<table class="table table-striped" id="mytable" width="100%">
<tr><td></td><td align="right">'.$st_lang['expenses_expended'].'</td>';
if (!empty($this->budget)) $s_out .= '<td align="right">'.$st_lang['expenses_budget'].'</td></tr>';

$total = 0;
$budget_total = 0;
foreach ($this->expenses as $key => $data) {
    $amount = $data['sum(e.amount)'];
    $current = $data['id'];
    $category_name = $data['name'];
    $total += $amount;
    $budget_amount = (isset($this->budget[$current])) ? $this->budget[$current] : 0;
    $budget_color = ($budget_amount <= $amount) ? '#FF0000' : '#00FF00';
    $s_out .= '<tr>'
        .'<td><a href="/expenses/index/category/'.$data['id'].'/month/'.$this->month.'/year/'.$this->year.'">'.$category_name.'</a></td>'
        .'<td align="right">'.number_format($amount,2).' &euro;</td>';
    if(!empty($this->budget)) {
        $s_out .= '<td align="right" style="color: '.$budget_color.';">'.$budget_amount.' &euro;</td>';
        $budget_total = $budget_total + $budget_amount;
    }
    $s_out .= '</tr>';
}
$s_out .= '<tr><td><B>TOTAL</B></td><td align="right"><B>'.number_format($total,2).' &euro;</B></td>';
if (!empty($this->budget)) {
    $budget_color = ($budget_total <= $total) ? '#FF0000' : '#00FF00';
    $s_out .= '<td align="right" style="color: '.$budget_color.';">'.number_format($budget_total,2).' &euro;</td>';
}
$s_out .= '</tr></table>';
?>

<script type="text/javascript">
    var pieData = <?php echo getJsonDataString($this->expenses); ?>;
    var pieTitle = "<?php echo $st_lang['expenses_monthly']; ?>";
    var barChartData = <?php echo $this->month_expenses; ?>;
    var barTitle = "<?php echo $st_lang['expenses_by_months']; ?>";
</script>

<?php
echo $s_out;
?>

<div id="expenses_all"></div>
<?php $this->getHelper('Web')->printToTop(); ?>
