# Generated by Django 3.1 on 2023-04-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moxie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
