# Generated by Django 3.1 on 2023-04-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moxie', '0004_auto_20230419_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='moxie.category'),
        ),
    ]
