# Generated by Django 3.1 on 2023-07-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moxie', '0008_auto_20230421_2327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
