# Generated by Django 3.1 on 2023-07-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moxie', '0009_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_owner',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.IntegerField(db_column='user_owner'),
        ),
    ]
