# Generated by Django 3.1 on 2023-07-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moxie', '0012_auto_20230706_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
