# Generated by Django 3.1 on 2023-07-07 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moxie', '0013_auto_20230706_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='user_owner',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
