# Generated by Django 3.1 on 2023-07-12 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moxie', '0015_auto_20230707_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='favourite', to='moxie.transaction'),
        ),
    ]
