# Generated by Django 3.1 on 2023-07-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moxie', '0017_auto_20230713_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='moxie.tag'),
        ),
        migrations.AlterField(
            model_name='transactiontag',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='moxie.transaction'),
        ),
    ]
