# Generated by Django 3.1 on 2023-07-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moxie', '0019_auto_20230718_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Expenses'), (2, 'Incomes'), (3, 'Both')]),
        ),
    ]
