# Generated by Django 3.1 on 2023-07-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moxie', '0021_sharedexpense_sharedexpensessheet_sharedexpensessheetusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedexpensessheet',
            name='closed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
