# Generated by Django 3.1 on 2023-07-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moxie', '0023_auto_20230728_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedexpense',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='moxie.sharedexpensessheet'),
        ),
    ]
