# Generated by Django 3.1 on 2023-07-29 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moxie', '0024_auto_20230728_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedexpensessheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_expenses_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedexpensessheetusers',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='moxie.sharedexpensessheet'),
        ),
        migrations.AlterField(
            model_name='sharedexpensessheetusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_shared_expenses_sheets', to=settings.AUTH_USER_MODEL),
        ),
    ]
