# Generated by Django 3.1 on 2023-08-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moxie', '0025_auto_20230729_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedexpensessheet',
            name='unique_id',
            field=models.CharField(max_length=64),
        ),
    ]
