# Generated by Django 3.1 on 2023-08-01 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moxie', '0026_auto_20230801_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_expenses', to='moxie.sharedexpensessheetusers'),
        ),
    ]
