# Generated by Django 3.1 on 2023-08-31 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moxie', '0028_moxieuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='moxieuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moxieuser_resource_file', to=settings.AUTH_USER_MODEL),
        ),
    ]
