<?php
global $st_lang;
$this->form->setAction('/login/registeruser')->setMethod('post');
?>
<center>
<div align="center" class="form-group" style="width: 400px">
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>">
<legend><?php echo $st_lang['register']; ?></legend>
<dl class="zend_form">
<?php
foreach ($this->form->getElements() as $element) {
	if($element->getLabel() != "Send") {
		echo '<dt id="'.$element->getId().'"><label for="'.$element->getId().'" class="optional">'.$element->getLabel().'</label></dt>';
		if($element->getType()=="Zend_Form_Element_Password")
			echo '<dd><input type="password" name="'.$element->getId().'" id="'.$element->getId().'" class="form-control"></dd>';
		else
			echo '<dd><input type="text" name="'.$element->getId().'" id="'.$element->getId().'" class="form-control"></dd>';
	}
}
?>
<dt id="captcha"><label for="captcha" class="optional">Captcha</label></dt>
<dd><input type="text" name="captcha" id="captcha" class="form-control"></dd>
<img src="<?php echo $_SESSION['captcha']['image_src']; ?>">

<dt id="submit-label">&#160;</dt><dd id="submit-element">
<input type="submit" name="submit" id="submit" value="Send" class="form-control btn btn-info"></dd>
</dl>
</form>
</div>
<p style="color: #ff0000; padding: 10px; border: 10px;"><?php echo $this->message; ?></p>
</center>