<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Error</title>
</head>
<body>
<h1>An error occurred</h1>

<?php

if (!isset($_SESSION['user_id'])) {
	echo 'You are not logged in. Please log in or register a new user.';
}
else {
	echo '<p>An error occurred; please try again later.</p>
	<pre style="bgcolor:blue">';
	echo $this->message;
	echo '</pre>';
}

?>
</body>
</html>