<script type="text/javascript" src="/js/incomes/data.js"></script>
<script type="text/javascript" src="/bower_components/chosen/chosen.jquery.js"></script>
<?php
global $st_lang;
$editSlug = '/incomes/edit/id/';
?>
<table width="100%">
<td><a href="/incomes/index/year/<?php echo $this->year-1; ?>"><div class="moxieicon moxieprevious"></div> <span class="moxieprevious"><?php echo $st_lang['incomes_last_year']; ?></span></a></td>
<td align="center"><span class="moxie_header_date"><?php echo date("Y", strtotime("01-01-".$this->year)); ?></span></td>
<td align="right"><a href="/incomes/index/year/<?php echo $this->year+1; ?>"><div class="moxieicon moxienext"></div> <span class="moxienext"><?php echo $st_lang['incomes_next_year']; ?></span></a></td>
</table>

<div id="form">
	<div class="moxie_expenses_form_div" style="float: left; width: 50%">
<?php
echo '<h2>'.$st_lang['income_header'].'</h2>';
$i_incomePK = $this->form->getValue('id');
if (isset($i_incomePK)) {
	echo '<form id="login" enctype="application/x-www-form-urlencoded" action="/incomes/update" method="post">';
	echo $this->form->getElement('user_owner');
	echo $this->form->getElement('id');
}
else {
	echo '<form id="login" enctype="application/x-www-form-urlencoded" action="/incomes/add" method="post">';
}
echo $this->form->getElement('amount');
echo $this->form->getElement('note');
?>
<dt id="date-label"><label for="date" class="optional"><?php echo $st_lang['incomes_date']; ?></label></dt>
<dd><input type="date" id="date" name="date" value="<?php echo $this->form->getValue('date'); ?>"></dd>
<?php
echo $this->form->getElement('category');
echo $this->form->getElement('submit');

if(isset($i_incomePK)) {
?>
<input type="button" class="moxiedelete" onclick='confirmDelete("<?php echo $i_incomePK; ?>")' value="<?php echo "Borrar"; ?>"/>
<?php
}
?>
	</form>
	</div>
	<div id="search_box" class="moxie_expenses_form_div" style="float: right; width: 50%">
		<?php
		echo $this->partial('common/filter.phtml', array('search_form' => $this->search_form));
		?>
	</div>
</div>
