<table width=100%>
<!-- Form + expenses list --> 
<tr>
<td>
<a href="/incomes/index/year/<?php echo $this->year-1; ?>">Last</a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="/incomes/index/year/<?php echo $this->year+1; ?>">Next</a>
<?php
echo $this->form;
?>

<?php
$f_finalAmount = 0;
$f_totalAmount = 0;
echo '
<table border=1 width=600 class="list">
';

foreach ($this->list as $key=>$value) {
	foreach ($value as $subkey => $subvalue) {
		$checked = ($subvalue->in_sum == 1) ? "checked":"";
		$datetime = explode(" ",$subvalue->date);
		echo '<tr>';
		echo '<td><input type="checkbox" class="my-checkbox" id="'.$subvalue->id.'" name="'.$subvalue->id.'" onClick="markLine('.$subvalue->id.');" '.$checked.'></td>';
		echo '<td align="right">'.number_format($subvalue->amount,2).' &euro;</td>';
		echo '<td align="center">'.$datetime[0].'</td>';
		echo '<td><div alt="'.$subvalue->note.'" title="'.$subvalue->note.'">'.$subvalue->note.'</div></td>';
		echo '</tr>';
		$f_totalAmount = $f_totalAmount + $subvalue->amount;
	}
	$f_finalAmount = $f_finalAmount + $f_totalAmount;
}
echo '<tr>
<td></td>
<td align="right">'.number_format($f_totalAmount,2).' &euro;</td><td colspan=3></td></tr>
</table>
';