<table width=100%>
<!-- Form + expenses list --> 
<tr>
<td>
<a href="/incomes/index/year/<?php echo $this->year-1; ?>">Last</a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="/incomes/index/year/<?php echo $this->year+1; ?>">Next</a>
<?php
$i_incomePK = $this->form->getElement('id');
if (isset($i_incomePK)) {
	echo '<form id="login" enctype="application/x-www-form-urlencoded" action="/incomes/update" method="post">';
	echo $this->form->getElement('user_owner');
	echo $this->form->getElement('id');
}
else {
	echo '<form id="login" enctype="application/x-www-form-urlencoded" action="/incomes/add" method="post">';
}
echo $this->form->getElement('amount');
echo $this->form->getElement('category');
echo "\n";
echo $this->form->getElement('note');
echo '<div class="date">'.$this->form->getValue('date').'</div>';
echo $this->form->getElement('submit');
echo '</form>';

?>

<?php
$f_totalAmount = 0;
echo '
<table border=1 width=100% class="list moxie" id="mytable">
<tr><td colspan="6"></tr>
';

foreach ($this->list as $key=>$value) {
	$checked = ($value['in_sum'] == 1) ? "checked":"";
	$s_dateGet = (isset($this->month) && isset($this->year)) ? '/year/'.$this->year.'/month/'.$this->month : '';
	$datetime = explode(" ",$value['date']);
	echo '
<tr>
<td class="list"><input type="checkbox" class="my-checkbox" id="'.$value['id'].'" name="'.$value['id'].'" onClick="markLine('.$value['id'].');" '.$checked.'></td>
<td class="list" width="16"><div class="moxieicon moxiedelete" onclick=\'confirmDelete("'.$value['id'].$s_dateGet.'")\'></div></td>
<td class="list" width="16"><a class="moxieedit" href="/incomes/edit/id/'.$value['id'].$s_dateGet.'"><div class="moxieicon moxieedit"></div></a></td>
<td class="list" align="right">'.number_format($value['amount'],2).' &euro;</td>
<td class="list" align="center">'.$datetime[0].'</td>
<td class="list" align="left">'.$value['name'].'</td>
<td><div alt="'.$value['note'].'" title="'.$value['note'].'">'.$value['note'].'</div></td>
</tr>';
	$f_totalAmount = $f_totalAmount + $value['amount'];
}
echo '<tr>
<td colspan=3></td>
<td align="right">'.number_format($f_totalAmount,2).' &euro;</td><td colspan=3></td></tr>';
?>
</table>