<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php global $st_lang; echo $st_lang['incomes']; ?></title>
<link rel="stylesheet" type="text/css" href="/moxie.css"/>
<link rel="stylesheet" type="text/css" href="/dropdown.css"/>
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" language="text/javascript">
	function confirmDelete(id) {
		var response;
		response = confirm("Are you sure you want to delete this income?");
		if (response == true) {
			window.location="/incomes/delete/id/"+id;
		}
	}

	$(document).ready(function() {
		init();
		$('#date_label').html("<?php echo $st_lang['incomes_date']; ?>");
	});
</script>
<link rel="stylesheet" type="text/css" href="/dropdown.css"/>
<script type="text/javascript" src="/js/zebra.js"></script>
<script type="text/javascript" src="/js/helpers.js"></script>
<script type="text/javascript" src="/js/calendar.js"></script>
<script type="text/javascript" src="/js/form.js"></script>
</head>
<body>
<?php
include '/html/web.php';
echo web_header(Zend_Registry::get('config')->moxie->app->name,
		Zend_Registry::get('config')->moxie->settings->url);
echo web_menu();
?>

<h2><?php echo $st_lang['incomes']; ?></h2>

<table>
<tr>
<td>
<?php
echo $this->partial('incomes/data.phtml',
					array('form'=>$this->form, 'list'=>$this->list,'year'=>$this->year));
?>
</td>
<td valign="top" width=50%>
<?php
echo $this->partial('incomes/stats.phtml',
					array('graphData' => $this->graphData, 'graphDataLabel' => $this->graphDataLabel, 'graphDataLabelYear' => $this->graphDataLabelYear));
?>
</td></tr></table>
</body>
</html>
