<?php
global $st_lang;
?>
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" language="text/javascript">
    var deleteUrl = "<?php echo Zend_Registry::get('config')->moxie->settings->url; ?>/incomes/delete/id/";
    var deleteMessage = "<?php echo $st_lang['incomes_delete_message']; ?>";
</script>

<table>
<tr>
<td>
<?php
echo $this->partial('incomes/data_header.phtml',
	array('form'=>$this->form, 'list'=>$this->list,'year'=>$this->year));
echo $this->partial('common/data.phtml',
	array('form'=>$this->form, 'list'=>$this->list,'year'=>$this->year, 'editSlug'  => '/incomes/edit/id/'));
?>
</td>
<td valign="top" width=50%>
<?php
echo $this->partial('incomes/stats.phtml',
					array('graphData' => $this->graphData, 'graphDataLabel' => $this->graphDataLabel, 'graphDataLabelYear' => $this->graphDataLabelYear));
?>
</td></tr></table>
