<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Incomes</title>
</head>
<body>

<h2>Incomes</h2>
<table width=100%>
<!-- Form + expenses list --> 
<tr>
<td>
<a href="/incomes/index/year/<?php echo $this->year-1; ?>">Last</a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="/incomes/index/year/<?php echo $this->year+1; ?>">Next</a>
<?php
echo $this->form;
?>

<?php
$f_finalAmount = 0;
$f_totalAmount = 0;
echo '
<table border=1 width=600>
';

foreach ($this->list as $key=>$value) {
	foreach ($value as $subkey => $subvalue) {
		$checked = ($subvalue->in_sum == 1) ? "checked":"";
		echo '<tr>';
		echo '<td><input type="checkbox" id="'.$subvalue->id.'" name="'.$subvalue->id.'" onClick="markLine('.$subvalue->id.');" '.$checked.'></td>';
		echo '<td>'.$subvalue->amount.' &euro;</td>';
		echo '<td>'.$subvalue->date.'</td>';
		echo '<td><div alt="'.$subvalue->note.'" title="'.$subvalue->note.'">'.$subvalue->note.'</div></td>';
		echo '</tr>';
		$f_totalAmount = $f_totalAmount + $subvalue->amount;
	}
	$f_finalAmount = $f_finalAmount + $f_totalAmount;
}
echo '<tr>
<td></td>
<td>'.number_format($f_totalAmount,2).' &euro;</td><td colspan=3></td></tr>
</table>
';
?>
</body>
</html>