<?php
// Catalan
$st_lang = array(
	// Index and menu
	'welcome' => 'Benvingut a ',
	'categories' => 'Categories',
	'budget'	=>	'Pressupost',
	'incomes'	=>	'Ingressos',
	'expenses'	=>	'Despeses',
	'stats'		=>	'Estadístiques',
	'index'		=>	'Inici',
	'about'		=>	'Aprop de',
	'benefits'	=>	'Avantatges',
	'finance' => 'Finances',
	'forgot_password'	=>	'Has oblidat la teva contrasenya?',
	'back_to_top' => 'Tornar a dalt',
	// Expenses
	'expenses_header'     => 'Afegir despesa',
	'expenses_amount'	=>	'Import',
	'expenses_category'	=>	'Categoria',
	'expenses_note'		=>	'Nota',
	'expenses_date'		=>	'Data',
	'expenses_send'		=>	'Enviar',
	'expenses_monthly'	=>	'Despesa mensual',
	'expenses_by_months'	=>	'Per mesos',
	'expenses_expended'	=>	'Gastat',
	'expenses_budget'	=>	'Pressupost',
	'expenses_mark'		=>	'Marcar:&nbsp;',
	'expenses_all'		=>	'Tots',
	'expenses_none'		=>	'Cap',
	'expenses_delete'   => 'Esborrar',
    'expenses_delete_message' => 'Esborrar aquesta despesa?',
	// Incomes
	'income_header'     => 'Afegir ingrés',
	'incomes_stats'		=>	'Gràfica d\'ingressos',
	'incomes_by_years'	=>	'Per anys',
	'incomes_yearly'	=>	'Ingressos anuals',
	'incomes_date'		=>	'Data',
    'incomes_delete_message' => 'Esborrar aquest ingrés?',
	// Search
	'search_header'     => 'Cerca',
	'search_tag'        => 'Tag',
	'search_note'       => 'Nota',
	'search_amount_min' => 'Import mínim',
	'search_amount_max' => 'Import màxim',
	'search_date_min'   => 'Data inicial',
	'search_date_max'   => 'Data final',
	'search_send'       => 'Cercar',
	// Transactions
	'in_sum_message'    => 'Mostrar al "Total"',
	'favourite_message'  => 'Favorit',
    'use_favourite' => 'Utilitzar favorit',
	// Budgets
	'budgets_title'     => 'Pressupostos',
	'budgets_save_successful' => 'Desat correctament',
	// Categories
	'categories_and_budget'	=>	'Categories i pressupost',
	'categories_delete'		=>	'Esborrar',
	'categories_edit'		=>	'Editar',
	'categories_income'		=>	'Ingrés',
	'categories_expense'	=>	'Despesa',
	'categories_both'		=>	'Despesa i ingŕes',
	'category_name'			=>	'Nom',
	'category_parent'		=>	'Categoria mare',
	'category_description'	=>	'Descripció',
	'category_type'			=>	'Tipus',
	'category_expense'		=>	'Despesa',
	'category_income'		=>	'Ingrés',
	'category_both'			=>	'Ambdues',
	'category_send'			=>	'Enviar',
	'category_new'			=>	'Nova categoria',
	// Stats
	'stats_title'	=>	'Estadístiques',
	'category'	=>	'Categoria',
	'total_this_year'	=>	'Total aquest any',
	'average_this_year'	=>	'Mitja aquest any',
	'average_unit'		=>	'Mitja d\'una compra',
	'total'		=>	'Total final',
	'average'	=>	'Mitja',
	'stats_budget_title' => 'Pressupost',
	'stats_budget_income' => 'TOTAL INGRESSOS',
	'stats_budget_expense' => 'TOTAL DESPESES',
	'stats_budget_total' => 'SALDO (Ingressos - Despeses)',
	'stats_trends' => 'Tendències',
	// Finance
	'finance_title' => 'Calculadora de depòsits',
	'finance_name' => 'Nom (opcional)',
    'finance_compare' => 'Comparar',
    'finance_add_row' => 'Afegir',
	'finance_amount' => 'Diners a depositar',
	'finance_interest' => 'Inter&egrave;s (%)',
	'finance_period' => 'Mesos',
	'finance_revenue' => 'Interessos',
	'finance_total' => 'Total',
    // Tags
    'tags_title' => 'Tags',
	'tags_notice' => 'En premer Actualitzar, s\'eliminaran els tags esborrats.',
	'tags_update' => 'Actualitzar',
	'tags_placeholder' => 'Introdueix tags...',
		// Shared expenses
		'sheets' => 'Despeses compartides',
		'sheets_no_sheets' => 'No tens fulls de despeses compartides.',
		'sheets_select_sheet' => 'Selecciona un full',
		'sheets_my_sheets' => 'Els meus fulls compartits',
		'sheets_create_new' => 'Crear nou full',
		'sheets_close' => 'Tancar full',
		'sheets_copy_to_my_account' => 'Copiar a les meves despeses',
		'sheets_using_category' => 'utilitzant la categoria&nbsp;',
		'sheets_create' => 'Crear',
		'sheets_name' => 'Nom',
		'sheets_add' => 'Afegir',
		'sheets_add_expense' => 'Afegir despesa',
		'sheets_add_user' => 'Afegir usuari',
		'sheets_add_user_message' => 'Introdueix l\'adreça de correu de la persona amb la que comparteixes despeses.&nbsp;'
		.'Si introdueixes un nom d\'usuari existent, vincularem aquest full al seu compte.',
		'sheets_copy_to_clipboard' => 'Copiar al porta-retalls',
		'sheets_email_subject' => 'Nou full de despeses compartides',
		'sheets_email_body_1' => 'Han compartit un full de despeses amb tu:',
		'sheets_email_body_2' => 'Si tienes cuenta en Moxie, podrás ver esta hoja en tus hojas de gastos'
		.' compartidos. En caso de que no tengas usuario, podrás registrarte y esta hoja quedará vinculada'
		.' a tu cuenta automáticamente.',
		'sheets_distribution' => 'Distribució',
	// User, login, etc.
	'users'		=>	'Configuració',
	'users_title'	=>	'Configuració',
	'users_my_account'	=>	'Usuari',
	'users_donate' => 'Donar',
	'new_user'	=>	'Nou usuari',
	'register'	=>	'Formulari de registre',
	'registration_ok'	=>	'<h2>Registre efectuat amb èxit!</h2>
Ja pots entrar amb el teu usuari i password per començar a utilitzar Moxie.',
	'registration_confirmed' => 'Usuari confirmat',
	'logout'	=>	'Sortir',
	'login'     =>  'Usuari',
	'password'  =>  'Contrasenya',
	'repeat_password' => 'Repeteix la contrasenya',
	'email'     => 'Email',
	'language'  => 'Idioma',
	'user_send' => 'Enviar',
	// Other stuff
		'emails_footer' => "Cordialment\n\nL\'equip de Moxie",
	'press_here_display' => '',
	'myaccount_password_error'	=>	'Error: Els passwords no coincideixen',
	'error_nouser' => 'No estàs identificat. Si us plau <a href="/">accedeix</a> o <a href="/login/newuser">registra\'t</a> com a usuari.',
	'text_about_title' => 'Aprop de...',
	'text_about_text' => 'Moxie utilitza:<br>
		<a href="http://www.php.net" target="blank">PHP</a><br>
		<a href="http://www.zend.com/" target="blank">Zend framework</a><br>
		<a href="https://developers.google.com/chart/" target="blank">Google charts</a><br>
		<a href="https://www.mysql.com/">MySQL</a><br>
		<a href="https://httpd.apache.org/">Apache</a><br><br>
        Moxie està hospedat a:<br>
        <a href="http://api.hostinger.es/redir/457908" target="blank">Hostinger.es</a><br><br>',

);
?>
