<?php
// English
$st_lang = array(
	// Index and menu
	'welcome' => 'Welcome to ',
	'categories' => 'Categories',
	'budget'	=>	'Budget',
	'incomes'	=>	'Incomes',
	'expenses'	=>	'Expenses',
	'stats'		=>	'Stats',
	'index'		=>	'Home',
	'about'		=>	'About',
	'benefits'	=>	'Benefits',
	'finance' => 'Finance',
	'forgot_password'	=>	'Forgot your password?',
	'back_to_top' => 'Back to top',
	// Expenses
	'expenses_header'     => 'Add expense',
    'expenses_edit'		=> 'Save',
	'expenses_amount'	=>	'Amount',
	'expenses_category'	=>	'Category',
	'expenses_note'		=>	'Note',
	'expenses_date'		=>	'Date',
	'expenses_send'		=>	'Send',
	'expenses_monthly'	=>	'Monthly expense',
	'expenses_by_months'	=>	'By months',
	'expenses_expended'	=>	'Expended',
	'expenses_budget'	=>	'Budget',
	'expenses_mark'		=>	'Mark:&nbsp;',
	'expenses_all'		=>	'All',
	'expenses_none'		=>	'None',
	'expenses_deca.plete'   => 'Delete',
    'expenses_delete_message' => 'Delete this expense?',
    'expenses_in_total' => 'In total sum',
    'expenses_not_in_total' => 'Out of total',
	// Incomes
	'income_header'     => 'Add income',
	'income_stats'		=>	'Income stats',
	'income_by_years'	=>	'By years',
	'incomes_yearly'	=>	'Yearly income',
	'incomes_date'		=>	'Date',
    'incomes_delete_message' => 'Delete this income?',
	// Search
	'search_header'     => 'Search',
	'search_tag'        => 'Tag',
	'search_note'       => 'Note',
	'search_amount_min' => 'Minimum amount',
	'search_amount_max' => 'Maximum amount',
	'search_date_min'   => 'Start date',
	'search_date_max'   => 'End date',
	'search_send'       => 'Search',
	// Transactions
	'in_sum_message'    => 'Show in "Total"',
	'favourite_message'  => 'Favourites',
    'favourites_message'  => 'Favourites',
    'use_favourite' => 'Use favourite',
    'empty_category' => 'Without category',
	// Budgets
	'budgets_title'     => 'Budgets',
	'budgets_save_successful' => 'Saved successfully',
	// Categories
	'categories_and_budget'	=>	'Categorias y presupuesto',
	'categories_delete'		=>	'Delete',
	'categories_edit'		=>	'Edit',
	'categories_income'		=>	'Income',
	'categories_expense'	=>	'Expense',
	'categories_both'		=>	'Both income and expense',
	'category_name'			=>	'Name',
	'category_parent'		=>	'Parent',
	'category_description'	=>	'Description',
	'category_type'			=>	'Type',
	'category_expense'		=>	'Expense',
	'category_income'		=>	'Income',
	'category_both'			=>	'Both',
	'category_send'			=>	'Send',
	'category_new'			=>	'New category',
	// Stats
	'stats_title'	=>	'Stats',
	'category'	=>	'Category',
	'total_this_year'	=>	'Total this year',
	'average_this_year'	=>	'Average this year',
	'average_unit'		=>	'Average of one buy',
	'total'		=>	'Total',
	'average'	=>	'Average',
	'stats_budget_title' => 'Budget',
	'stats_budget_income' => 'TOTAL INCOME',
	'stats_budget_expense' => 'TOTAL EXPENSE',
	'stats_budget_total' => 'BALANCE (Income - expense)',
	'stats_trends' => 'Trends',
    'stats_anual_positive' => 'POSITIVE FLOW',
    'stats_anual_negative' => 'POSITIVE FLOW',
	// Finance
	'finance_title' => 'Deposit calculator',
	'finance_name' => 'Name (optional)',
    'finance_compare' => 'Compare',
    'finance_add_row' => 'Add',
	'finance_amount' => 'Amount to deposit',
	'finance_interest' => 'Interest (%)',
	'finance_period' => 'Months',
	'finance_revenue' => 'Interests',
	'finance_total' => 'Total',
    // Tags
    'tags_title' => 'Tags',
	'tags_notice' => 'When pressing Update, removed tags will be deleted.',
	'tags_update' => 'Update',
	'tags_placeholder' => 'Enter tags...',
		// Shared expenses
		'sheets' => 'Shared expenses',
		'sheets_no_sheets' => 'You do not have shared expenses sheets.',
		'sheets_select_sheet' => 'Select a sheet',
		'sheets_my_sheets' => 'My shared sheets',
		'sheets_create_new' => 'Create new sheet',
		'sheets_close' => 'Close sheet',
		'sheets_copy_to_my_account' => 'Copy to my expenses',
		'sheets_create' => 'Create',
		'sheets_name' => 'Name',
		'sheets_add' => 'Add',
		'sheets_add_expense' => 'Add expense',
		'sheets_add_user' => 'Add user',
		'sheets_add_user_message' => 'Enter address of person with whom you are sharing expenses.&nbsp;'
		.'If you enter an existing username, the sheet will be added to the user account.',
		'sheets_copy_to_clipboard' => 'Copy permalink of this page to clipboard',
		'sheets_email_subject' => 'New shared expenses sheet',
		'sheets_email_body_1' => 'Someone shared an expenses sheet with you:',
		'sheets_email_body_2' => 'If you have a Moxie account, you will see this sheet in your shared expenses sheets.'
		.'If you do not have an account, you can register and this sheet will be linked to your account'
		.' automatically.',
		'sheets_distribution' => 'Distribution',
    	'sheets_apply_to_all' => 'Apply to all',
    'sheets_currency' => 'Currency',
    'sheets_currency_change' => 'Change (from your local currency to this)',
    'sheets_in_currency' => 'In sheet currency?',
    'sheets_using_this_currency' => 'Use this change rate for sheet currency',
    'sheets_already_copied' => 'Already copied',
	// User, login, etc.
	'users'		=>	'Settings',
	'users_title'	=>	'Settings',
	'users_my_account'	=>	'My account',
	'users_donate' => 'Donate',
	'new_user'	=>	'New user',
	'register'	=>	'Registration form',
	'registration_ok'	=>	'<h2>Registration successfully!</h2>
Now you can log in with your login and password to start using Moxie.',
	'registration_confirmed' => 'User confirmed',
	'logout'	=>	'Logout',
	'login'     =>  'Login',
	'password'  =>  'Password',
	'repeat_password' => 'Repeat password',
	'email'     => 'Email',
	'language'  => 'Language',
	'user_send' => 'Send',
	// Other stuff
		'emails_footer' => "Best regards\n\nMoxie team",
	'press_here_display' => '',
	'myaccount_password_error'	=>	'Error: Passwords do not match',
	'error_nouser' => 'You are not logged in. Please <a href="/">log in</a> or <a href="login/newuser">register</a> a new user.',
	'text_about_title' => 'About...',
	'text_about_text' => '
Moxie is helped, through licenses, from:<br>
<a href="https://www.jetbrains.com/phpstorm/">JetBrains</a><br><br>
Moxie uses:<br> 
		<a href="http://www.php.net" target="blank">PHP</a><br>
		<a href="http://www.zend.com/" target="blank">Zend framework</a><br>
		<a href="https://developers.google.com/chart/" target="blank">Google charts</a><br>
		<a href="https://www.mysql.com/">MySQL</a><br>
		<a href="https://httpd.apache.org/">Apache</a><br><br>
         Moxie is hosted at:<br>
         <a href="https://www.ovh.com/" target="blank">OVH</a><br><br>',

);
?>
